-- File generated by Mangos Online Translation Editor (MOTE) v2.00
SET NAMES 'utf8';
UPDATE locales_page_text SET text_loc5='許久以前，當只有北風精靈統治群山時，一個強大坦卡族酋長的兄弟試圖將這些土地據為己有。' WHERE entry=3280;
UPDATE locales_page_text SET text_loc5='獻給那些在冰凍荒原和天譴軍團交戰時倒下的人們。' WHERE entry=3605;
UPDATE locales_page_text SET text_loc5='月亮照耀著山谷' WHERE entry=3683;
UPDATE locales_page_text SET text_loc5='漫遊者格里雷克' WHERE entry=3686;
UPDATE locales_page_text SET text_loc5='古拉巴什的毀滅' WHERE entry=3689;
UPDATE locales_page_text SET text_loc5='帝王之墓' WHERE entry=3698;
UPDATE locales_page_text SET text_loc5='我找到了一個不得了的地方!$B$B這整塊區域都迴盪著古老建築的共鳴。$B$B要不是現在天色已晚，我一定會立刻衝進裡頭進行調查!$B$B今晚要安心睡一覺可難囉...' WHERE entry=3710;
UPDATE locales_page_text SET text_loc5='今天是收穫最豐富的一天!$B$B這個房間的確是遠古之源，擁有不可思議的機關結構，但看起來已經荒廢已久。$B$B我明天會多做些調查。$B$B這項發現一定可以強迫舒諾茲重視我!$B$B他沒理由在我發現了這個後還不讓我升職吧?' WHERE entry=3711;

SET NAMES 'latin1';
