-- File generated by Mangos Online Translation Editor (MOTE) v2.0
SET NAMES 'utf8';
UPDATE locales_achievement_reward SET subject_loc9='Per l\'Alleanza!' WHERE entry=614;
UPDATE locales_achievement_reward SET subject_loc9='Avanti tutta, Ammiraglio!' WHERE entry=871;
UPDATE locales_achievement_reward SET subject_loc9='Il Diplomatico' WHERE entry=942;
UPDATE locales_achievement_reward SET subject_loc9='Il Diplomatico' WHERE entry=943;

SET NAMES 'latin1';
