-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc9='Zaldimar Wefhellt' WHERE entry=2; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc9='La Rosa Dorata' WHERE entry=22; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visitatori di Stormwind' WHERE entry=24; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Champions\' Hall' WHERE entry=28; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Parco' WHERE entry=32; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Agnello Macellato' WHERE entry=38; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=40; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna del Maiale e del Fischietto' WHERE entry=42; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=47; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='Tessili di Duncan' WHERE entry=49; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Ironforge' WHERE entry=50; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc9='Deeprun Tram' WHERE entry=52; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visite di Ironforge' WHERE entry=54; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozioni e Bevande Varie di Berryfizz' WHERE entry=66; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc9='The Great Forge' WHERE entry=67; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Ramino di Bronzo' WHERE entry=68; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Arcani di Thistlefuzz' WHERE entry=69; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=70; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Pescatore Itinerante' WHERE entry=71; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=73; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Vestiario di Stonebrow' WHERE entry=75; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Darnassus' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=176; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Ambasciata dell\'Orda' WHERE entry=178; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Orgrimmar' WHERE entry=181; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Hall of Legends' WHERE entry=186; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Thunder Bluff' WHERE entry=275; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc9='Informazioni Civiche di Thunder Bluff' WHERE entry=277; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Anziani' WHERE entry=285; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=286; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Spiriti' WHERE entry=288; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimia di Bena' WHERE entry=289; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc9='Fucina di Karn' WHERE entry=290; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc9='Cucina di Aska' WHERE entry=291; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc9='Incantatori Dawnstrider' WHERE entry=292; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc9='Cure Spirituali' WHERE entry=293; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc9='Esca & Attrezzatura da Pesca Mountaintop' WHERE entry=294; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc9='Erbalismo Holistic' WHERE entry=295; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=297; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Geologia Stonehoof' WHERE entry=298; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione Darkbriar' WHERE entry=301; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione dello Spirito' WHERE entry=302; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=303; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratellanza Shadowswift' WHERE entry=304; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc9='Enclave di Darkfire' WHERE entry=305; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Coraggiosi' WHERE entry=306; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchemi e Pozioni di Yelmak' WHERE entry=307; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Incudine Bruciante' WHERE entry=308; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozza del Fuoco di Borstan' WHERE entry=309; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc9='Lavori Runici di Godan' WHERE entry=310; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc9='Officina di Nogg' WHERE entry=311; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc9='Sopravvivenza dei Più Adatti' WHERE entry=312; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc9='Pesca di Lumak' WHERE entry=313; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc9='Arboreto di Jandi' WHERE entry=314; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc9='Estrazioni del Canyon Rosso' WHERE entry=315; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=316; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Tessili di Magar' WHERE entry=317; /* icon_name: Magar\'s Cloth Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='The Apothecarium' WHERE entry=336; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc9='Gadget di Springspindle' WHERE entry=401; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc9='Zaldimar Wefhellt' WHERE entry=1002; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc9='La Rosa Dorata' WHERE entry=1026; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visitatori di Stormwind' WHERE entry=1028; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Champions\' Hall' WHERE entry=1032; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Parco' WHERE entry=1036; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Agnello Macellato' WHERE entry=1043; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=1045; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna del Maiale e del Fischietto' WHERE entry=1048; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=1053; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=1055; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=1057; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='Tessili di Duncan' WHERE entry=1058; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Ironforge' WHERE entry=1059; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visite di Ironforge' WHERE entry=1066; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=1077; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=1078; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=1079; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Ramino di Bronzo' WHERE entry=1080; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=1085; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozioni e Bevande Varie di Berryfizz' WHERE entry=1087; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc9='The Great Forge' WHERE entry=1088; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc9='Deeprun Tram' WHERE entry=1089; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Arcani di Thistlefuzz' WHERE entry=1090; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc9='Gadget di Springspindle' WHERE entry=1092; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=1093; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Pescatore Itinerante' WHERE entry=1094; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=1095; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=1098; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=1100; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Vestiario di Stonebrow' WHERE entry=1101; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Darnassus' WHERE entry=1123; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=1186; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Ambasciata dell\'Orda' WHERE entry=1188; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Orgrimmar' WHERE entry=1193; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Hall of Legends' WHERE entry=1201; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione Darkbriar' WHERE entry=1207; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchemi e Pozioni di Yelmak' WHERE entry=1208; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione dello Spirito' WHERE entry=1209; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=1210; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratellanza Shadowswift' WHERE entry=1211; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc9='Enclave di Darkfire' WHERE entry=1212; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Coraggiosi' WHERE entry=1213; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=1214; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Incudine Bruciante' WHERE entry=1215; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozza del Fuoco di Borstan' WHERE entry=1216; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc9='Lavori Runici di Godan' WHERE entry=1220; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc9='Officina di Nogg' WHERE entry=1222; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc9='Sopravvivenza dei Più Adatti' WHERE entry=1223; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc9='Pesca di Lumak' WHERE entry=1224; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc9='Arboreto di Jandi' WHERE entry=1225; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=1227; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Estrazioni del Canyon Rosso' WHERE entry=1228; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=1229; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Tessili di Magar' WHERE entry=1230; /* icon_name: Magar\'s Cloth Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='The Apothecarium' WHERE entry=1246; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Thunder Bluff' WHERE entry=1303; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc9='Informazioni Civiche di Thunder Bluff' WHERE entry=1305; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Anziani' WHERE entry=1314; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=1315; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Spiriti' WHERE entry=1319; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=1320; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Fucina di Karn' WHERE entry=1323; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimia di Bena' WHERE entry=1324; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc9='Cucina di Aska' WHERE entry=1325; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc9='Incantatori Dawnstrider' WHERE entry=1326; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc9='Cure Spirituali' WHERE entry=1327; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc9='Esca & Attrezzatura da Pesca Mountaintop' WHERE entry=1328; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc9='Erbalismo Holistic' WHERE entry=1329; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=1331; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Geologia Stonehoof' WHERE entry=1332; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=1334; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=1901; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=12627; /* icon_name: Bank of Orgrimmar */

SET NAMES 'latin1';
