-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda del Fiero Leone' WHERE entry=1; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Zaldimar Wefhellt' WHERE entry=2; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratello Wilhelm' WHERE entry=3; /* icon_name: Brother Wilhelm */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimista Mallory' WHERE entry=8; /* icon_name: Alchemist Mallory */
UPDATE locales_points_of_interest SET icon_name_loc9='Smith Argus' WHERE entry=9; /* icon_name: Smith Argus */
UPDATE locales_points_of_interest SET icon_name_loc9='Tomas' WHERE entry=10; /* icon_name: Tomas */
UPDATE locales_points_of_interest SET icon_name_loc9='Adele Fielder' WHERE entry=14; /* icon_name: Adele Fielder */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Roccavento' WHERE entry=18; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Porto di Roccavento' WHERE entry=20; /* icon_name: Stormwind Harbor */
UPDATE locales_points_of_interest SET icon_name_loc9='La Rosa Dorata' WHERE entry=22; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visitatori di Stormwind' WHERE entry=24; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Woo Ping' WHERE entry=27; /* icon_name: Woo Ping */
UPDATE locales_points_of_interest SET icon_name_loc9='Champions\' Hall' WHERE entry=28; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Stormwind' WHERE entry=29; /* icon_name: Battlemasters Stormwind */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Parco' WHERE entry=32; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc9='Santuario del Mago' WHERE entry=34; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc9='Cathedral Of Light' WHERE entry=35; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Agnello Macellato' WHERE entry=38; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=40; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='Therum Deepforge' WHERE entry=41; /* icon_name: Therum Deepforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna del Maiale e del Fischietto' WHERE entry=42; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='Arnold Leland' WHERE entry=46; /* icon_name: Arnold Leland */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=47; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='Tessili di Duncan' WHERE entry=49; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Ironforge' WHERE entry=50; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc9='Deeprun Tram' WHERE entry=52; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visite di Ironforge' WHERE entry=54; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Ulbrek Firehand' WHERE entry=57; /* icon_name: Ulbrek Firehand */
UPDATE locales_points_of_interest SET icon_name_loc9='Bixi e Buliwyf' WHERE entry=58; /* icon_name: Bixi and Buliwyf */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Ironforge' WHERE entry=59; /* icon_name: Battlemasters Ironforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozioni e Bevande Varie di Berryfizz' WHERE entry=66; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc9='The Great Forge' WHERE entry=67; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Ramino di Bronzo' WHERE entry=68; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Arcani di Thistlefuzz' WHERE entry=69; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=70; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Pescatore Itinerante' WHERE entry=71; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=73; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Vestiario di Stonebrow' WHERE entry=75; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc9='Distilleria Birratuono' WHERE entry=76; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc9='Shelby Stoneflint' WHERE entry=77; /* icon_name: Shelby Stoneflint */
UPDATE locales_points_of_interest SET icon_name_loc9='Azar Stronghammer' WHERE entry=80; /* icon_name: Azar Stronghammer */
UPDATE locales_points_of_interest SET icon_name_loc9='Tognus Flintfire' WHERE entry=85; /* icon_name: Tognus Flintfire */
UPDATE locales_points_of_interest SET icon_name_loc9='Paxton Ganter' WHERE entry=88; /* icon_name: Paxton Ganter */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Darnassus' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Alassin' WHERE entry=95; /* icon_name: Alassin */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Darnassus' WHERE entry=97; /* icon_name: Battlemasters Darnassus */
UPDATE locales_points_of_interest SET icon_name_loc9='Terrazza dei Guerrieri' WHERE entry=101; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc9='Seriadne' WHERE entry=112; /* icon_name: Seriadne */
UPDATE locales_points_of_interest SET icon_name_loc9='Cyndra Kindwhisper' WHERE entry=118; /* icon_name: Cyndra Kindwhisper */
UPDATE locales_points_of_interest SET icon_name_loc9='Zarrin' WHERE entry=119; /* icon_name: Zarrin */
UPDATE locales_points_of_interest SET icon_name_loc9='Alanna Raveneye' WHERE entry=120; /* icon_name: Alanna Raveneye */
UPDATE locales_points_of_interest SET icon_name_loc9='Byancie' WHERE entry=121; /* icon_name: Byancie */
UPDATE locales_points_of_interest SET icon_name_loc9='Entrata Est delle Fogne di Dalaran' WHERE entry=126; /* icon_name: Dalaran Eastern Sewer Entrance */
UPDATE locales_points_of_interest SET icon_name_loc9='Barbiere di Dalaran' WHERE entry=133; /* icon_name: Dalaran Barber */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante di Volo di Dalaran' WHERE entry=134; /* icon_name: Dalaran Flight Master */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro d\'Accoglienza di Dalaran' WHERE entry=135; /* icon_name: Dalaran Visitor Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda di Dalaran' WHERE entry=136; /* icon_name: Dalaran Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda dell\'Allenza di Dalaran' WHERE entry=137; /* icon_name: Dalaran Alliance Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda dell\'Orda di Dalaran' WHERE entry=138; /* icon_name: Dalaran Horde Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Fabbro di Dalaran' WHERE entry=139; /* icon_name: Dalaran Locksmith */
UPDATE locales_points_of_interest SET icon_name_loc9='Memoriale Antonidas di Dalaran' WHERE entry=144; /* icon_name: Dalaran Antonidas Memorial */
UPDATE locales_points_of_interest SET icon_name_loc9='Dalaran Eventide' WHERE entry=146; /* icon_name: Dalaran Eventide */
UPDATE locales_points_of_interest SET icon_name_loc9='Cimitero di Dalaran' WHERE entry=147; /* icon_name: Dalaran Cemetary */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante d\'Iscrizioni di Dalaran' WHERE entry=148; /* icon_name: Dalaran Inscription Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Mago di Dalaran' WHERE entry=150; /* icon_name: Dalaran Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnate Alchimista di Dalaran' WHERE entry=151; /* icon_name: Dalaran Alchemy Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Fabbro di Dalaran' WHERE entry=152; /* icon_name: Dalaran Blacksmithing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Incantatore di Dalaran' WHERE entry=153; /* icon_name: Dalaran Enchanting Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Ingeniere di Dalaran' WHERE entry=154; /* icon_name: Dalaran Engineering Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante di Primo soccorso di Dalaran' WHERE entry=155; /* icon_name: Dalaran First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Fontana di Pesca di Dalaran' WHERE entry=156; /* icon_name: Dalaran Fishing Fountain */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Erborista di Dalaran' WHERE entry=157; /* icon_name: Dalaran Herbalism Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnate Gioelliere di Dalaran' WHERE entry=158; /* icon_name: Dalaran Jewelcrafting Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Conciatore di Dalaran' WHERE entry=159; /* icon_name: Dalaran Leatherworking Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Vestiti e Armature di Tessuto di Dalaran' WHERE entry=163; /* icon_name: Dalaran Cloth Armor & Clothing */
UPDATE locales_points_of_interest SET icon_name_loc9='Fioraio di Dalaran' WHERE entry=164; /* icon_name: Dalaran Flowers */
UPDATE locales_points_of_interest SET icon_name_loc9='Fruttivendolo di Dalaran' WHERE entry=165; /* icon_name: Dalaran Fruit Vendor */
UPDATE locales_points_of_interest SET icon_name_loc9='Emporio e Mercato di Dalaran' WHERE entry=166; /* icon_name: Dalaran General & Trade Store */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=176; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Ambasciata dell\'Orda' WHERE entry=178; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Orgrimmar' WHERE entry=181; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Sayoc & Hanashi' WHERE entry=184; /* icon_name: Sayoc & Hanashi */
UPDATE locales_points_of_interest SET icon_name_loc9='Xon\'cha' WHERE entry=185; /* icon_name: Xon\'cha */
UPDATE locales_points_of_interest SET icon_name_loc9='Hall of Legends' WHERE entry=186; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Orgrimmar' WHERE entry=187; /* icon_name: Battlemasters Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Locandiere, Azure Watch' WHERE entry=219; /* icon_name: Azure Watch, Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc9='Stalliere, Azure Watch' WHERE entry=220; /* icon_name: Azure Watch, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Cacciatore, Azure Watch' WHERE entry=221; /* icon_name: Azure Watch, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Mago, Azure Watch' WHERE entry=222; /* icon_name: Azure Watch, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Paladino, Azure Watch' WHERE entry=223; /* icon_name: Azure Watch, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Sacerdote, Azure Watch' WHERE entry=224; /* icon_name: Azure Watch, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Sciamano, Azure Watch' WHERE entry=225; /* icon_name: Azure Watch, Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Guerriero, Azure Watch' WHERE entry=226; /* icon_name: Azure Watch, Warrior Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimista, Azure Watch' WHERE entry=227; /* icon_name: Azure Watch, Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante di Ingegneria, Azure Watch' WHERE entry=230; /* icon_name: Azure Watch, Engineering Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante di Primo soccorso, Azure Watch' WHERE entry=231; /* icon_name: Azure Watch, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Ammen Ford, Pescatrice' WHERE entry=232; /* icon_name: Ammen Ford, Fisherwoman */
UPDATE locales_points_of_interest SET icon_name_loc9='Erborista, Azure Watch' WHERE entry=233; /* icon_name: Azure Watch, Herbalist */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Minatore, Azure Watch' WHERE entry=235; /* icon_name: Azure Watch, Mining Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Armature di Cuoio e Maglia di Dalaran' WHERE entry=238; /* icon_name: Dalaran Leather & Mail Armor */
UPDATE locales_points_of_interest SET icon_name_loc9='Mercante di Gemme Aldor' WHERE entry=259; /* icon_name: Aldor Gem Vendor */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Arene di Exodar' WHERE entry=264; /* icon_name: Arena Battlemaster Exodar */
UPDATE locales_points_of_interest SET icon_name_loc9='Tempio della Luna' WHERE entry=267; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Thunder Bluff' WHERE entry=275; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc9='Informazioni Civiche di Thunder Bluff' WHERE entry=277; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc9='Ansekhwa' WHERE entry=281; /* icon_name: Ansekhwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Bulrug' WHERE entry=282; /* icon_name: Bulrug */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Thunder Bluff' WHERE entry=283; /* icon_name: Battlemasters Thunder Bluff */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Anziani' WHERE entry=285; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=286; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozze delle Visioni' WHERE entry=287; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Spiriti' WHERE entry=288; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimia di Bena' WHERE entry=289; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc9='Fucina di Karn' WHERE entry=290; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc9='Cucina di Aska' WHERE entry=291; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc9='Incantatori Dawnstrider' WHERE entry=292; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc9='Cure Spirituali' WHERE entry=293; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc9='Esca & Attrezzatura da Pesca Mountaintop' WHERE entry=294; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc9='Erbalismo Holistic' WHERE entry=295; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=297; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Geologia Stonehoof' WHERE entry=298; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione Darkbriar' WHERE entry=301; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione dello Spirito' WHERE entry=302; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=303; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratellanza Shadowswift' WHERE entry=304; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc9='Enclave di Darkfire' WHERE entry=305; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Coraggiosi' WHERE entry=306; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchemi e Pozioni di Yelmak' WHERE entry=307; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Incudine Bruciante' WHERE entry=308; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozza del Fuoco di Borstan' WHERE entry=309; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc9='Lavori Runici di Godan' WHERE entry=310; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc9='Officina di Nogg' WHERE entry=311; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc9='Sopravvivenza dei Più Adatti' WHERE entry=312; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc9='Pesca di Lumak' WHERE entry=313; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc9='Arboreto di Jandi' WHERE entry=314; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc9='Estrazioni del Canyon Rosso' WHERE entry=315; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=316; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Tessili di Magar' WHERE entry=317; /* icon_name: Magar\'s Cloth Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Sepulcra' WHERE entry=318; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Undercity' WHERE entry=322; /* icon_name: Battlemasters Undercity */
UPDATE locales_points_of_interest SET icon_name_loc9='Anya Maulray' WHERE entry=327; /* icon_name: Anya Maulray */
UPDATE locales_points_of_interest SET icon_name_loc9='Archibald' WHERE entry=328; /* icon_name: Archibald */
UPDATE locales_points_of_interest SET icon_name_loc9='Campione Cyssa Dawnrose' WHERE entry=330; /* icon_name: Champion Cyssa Dawnrose */
UPDATE locales_points_of_interest SET icon_name_loc9='The Apothecarium' WHERE entry=336; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc9='Istruttore dei Paladini di Piazza del Falco' WHERE entry=387; /* icon_name: Falconwing Square, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Gadget di Springspindle' WHERE entry=401; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc9='Yarr Hammerstone' WHERE entry=402; /* icon_name: Yarr Hammerstone */
UPDATE locales_points_of_interest SET icon_name_loc9='Shoja\'my' WHERE entry=404; /* icon_name: Shoja\'my */
UPDATE locales_points_of_interest SET icon_name_loc9='Thotar' WHERE entry=405; /* icon_name: Thotar */
UPDATE locales_points_of_interest SET icon_name_loc9='Un\'Thuwa' WHERE entry=406; /* icon_name: Un\'Thuwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Tai\'jin' WHERE entry=407; /* icon_name: Tai\'jin */
UPDATE locales_points_of_interest SET icon_name_loc9='Rawrk' WHERE entry=415; /* icon_name: Rawrk */
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda di Bloodhoof Village' WHERE entry=419; /* icon_name: Bloodhoof Village Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Seikwa' WHERE entry=420; /* icon_name: Seikwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Yaw Sharpmane' WHERE entry=422; /* icon_name: Yaw Sharpmane */
UPDATE locales_points_of_interest SET icon_name_loc9='Vira Younghoof' WHERE entry=426; /* icon_name: Vira Younghoof */
UPDATE locales_points_of_interest SET icon_name_loc9='Chaw Stronghide' WHERE entry=428; /* icon_name: Chaw Stronghide */
UPDATE locales_points_of_interest SET icon_name_loc9='Yonn Deepcut' WHERE entry=429; /* icon_name: Yonn Deepcut */
UPDATE locales_points_of_interest SET icon_name_loc9='Cain Firesong' WHERE entry=433; /* icon_name: Cain Firesong */
UPDATE locales_points_of_interest SET icon_name_loc9='Rupert Boch' WHERE entry=436; /* icon_name: Rupert Boch */
UPDATE locales_points_of_interest SET icon_name_loc9='Austil de Mon' WHERE entry=437; /* icon_name: Austil de Mon */
UPDATE locales_points_of_interest SET icon_name_loc9='Carolai Anise' WHERE entry=438; /* icon_name: Carolai Anise */
UPDATE locales_points_of_interest SET icon_name_loc9='Vance Undergloom' WHERE entry=439; /* icon_name: Vance Undergloom */
UPDATE locales_points_of_interest SET icon_name_loc9='Clyde Kellen' WHERE entry=441; /* icon_name: Clyde Kellen */
UPDATE locales_points_of_interest SET icon_name_loc9='Shelene Rhobart' WHERE entry=443; /* icon_name: Shelene Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc9='Rand Rhobart' WHERE entry=444; /* icon_name: Rand Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc9='Bowen Brisboise' WHERE entry=445; /* icon_name: Bowen Brisboise */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna dell\'Impiccato' WHERE entry=446; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='Brewfest Souvenirs' WHERE entry=448; /* icon_name: Brewfest Souvenirs */
UPDATE locales_points_of_interest SET icon_name_loc9='Corsa dei Montoni del Brewfest' WHERE entry=449; /* icon_name: Brewfest Ram Racing */
UPDATE locales_points_of_interest SET icon_name_loc9='Club Birra del Mese, Ironforge' WHERE entry=450; /* icon_name: Brew of the Month Club, Ironforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Club Birra del Mese, Orgrimmar' WHERE entry=453; /* icon_name: Brew of the Month Club, Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Insegnante Archeologo di Dalaran' WHERE entry=454; /* icon_name: Dalaran Archaeology Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='AAA Tonk Arena' WHERE entry=463; /* icon_name: AAA Tonk Arena */
UPDATE locales_points_of_interest SET icon_name_loc9='AAA Cannone' WHERE entry=464; /* icon_name: AAA Cannon */
UPDATE locales_points_of_interest SET icon_name_loc9='AAA Colpisci uno Gnall' WHERE entry=465; /* icon_name: AAA Whack-a-Gnoll */
UPDATE locales_points_of_interest SET icon_name_loc9='AAA Lancio degli Anelli' WHERE entry=466; /* icon_name: AAA Ring Toss */
UPDATE locales_points_of_interest SET icon_name_loc9='AAA Tiro a Segno' WHERE entry=467; /* icon_name: AAA Shooting Gallery */
UPDATE locales_points_of_interest SET icon_name_loc9='AAA Indovino' WHERE entry=468; /* icon_name: AAA Fortune Teller */
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda del Fiero Leone' WHERE entry=1000; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Zaldimar Wefhellt' WHERE entry=1002; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratello Wilhelm' WHERE entry=1003; /* icon_name: Brother Wilhelm */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimista Mallory' WHERE entry=1008; /* icon_name: Alchemist Mallory */
UPDATE locales_points_of_interest SET icon_name_loc9='Smith Argus' WHERE entry=1009; /* icon_name: Smith Argus */
UPDATE locales_points_of_interest SET icon_name_loc9='Tomas' WHERE entry=1010; /* icon_name: Tomas */
UPDATE locales_points_of_interest SET icon_name_loc9='Adele Fielder' WHERE entry=1017; /* icon_name: Adele Fielder */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Roccavento' WHERE entry=1020; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Porto di Roccavento' WHERE entry=1023; /* icon_name: Stormwind Harbor */
UPDATE locales_points_of_interest SET icon_name_loc9='La Rosa Dorata' WHERE entry=1026; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visitatori di Stormwind' WHERE entry=1028; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Woo Ping' WHERE entry=1031; /* icon_name: Woo Ping */
UPDATE locales_points_of_interest SET icon_name_loc9='Champions\' Hall' WHERE entry=1032; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Stormwind' WHERE entry=1034; /* icon_name: Battlemasters Stormwind */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Parco' WHERE entry=1036; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc9='Santuario del Mago' WHERE entry=1038; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc9='Cathedral Of Light' WHERE entry=1039; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc9='Cathedral Of Light' WHERE entry=1040; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Agnello Macellato' WHERE entry=1043; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=1045; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='Therum Deepforge' WHERE entry=1046; /* icon_name: Therum Deepforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna del Maiale e del Fischietto' WHERE entry=1048; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='Arnold Leland' WHERE entry=1052; /* icon_name: Arnold Leland */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=1053; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=1055; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=1057; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='Tessili di Duncan' WHERE entry=1058; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Ironforge' WHERE entry=1059; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visite di Ironforge' WHERE entry=1066; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Ulbrek Firehand' WHERE entry=1071; /* icon_name: Ulbrek Firehand */
UPDATE locales_points_of_interest SET icon_name_loc9='Bixi e Buliwyf' WHERE entry=1072; /* icon_name: Bixi and Buliwyf */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Ironforge' WHERE entry=1076; /* icon_name: Battlemasters Ironforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=1077; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=1078; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=1079; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Ramino di Bronzo' WHERE entry=1080; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=1085; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozioni e Bevande Varie di Berryfizz' WHERE entry=1087; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc9='The Great Forge' WHERE entry=1088; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc9='Deeprun Tram' WHERE entry=1089; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Arcani di Thistlefuzz' WHERE entry=1090; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc9='Gadget di Springspindle' WHERE entry=1092; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=1093; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Pescatore Itinerante' WHERE entry=1094; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=1095; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=1098; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=1100; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Vestiario di Stonebrow' WHERE entry=1101; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc9='Distilleria Birratuono' WHERE entry=1102; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc9='Shelby Stoneflint' WHERE entry=1106; /* icon_name: Shelby Stoneflint */
UPDATE locales_points_of_interest SET icon_name_loc9='Azar Stronghammer' WHERE entry=1109; /* icon_name: Azar Stronghammer */
UPDATE locales_points_of_interest SET icon_name_loc9='Tognus Flintfire' WHERE entry=1115; /* icon_name: Tognus Flintfire */
UPDATE locales_points_of_interest SET icon_name_loc9='Paxton Ganter' WHERE entry=1119; /* icon_name: Paxton Ganter */
UPDATE locales_points_of_interest SET icon_name_loc9='Yarr Hammerstone' WHERE entry=1122; /* icon_name: Yarr Hammerstone */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Darnassus' WHERE entry=1123; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Rut\'theran' WHERE entry=1125; /* icon_name: Rut\'theran Village */
UPDATE locales_points_of_interest SET icon_name_loc9='Alassin' WHERE entry=1130; /* icon_name: Alassin */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Darnassus' WHERE entry=1132; /* icon_name: Battlemasters Darnassus */
UPDATE locales_points_of_interest SET icon_name_loc9='Tempio della Luna' WHERE entry=1135; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc9='Terrazza dei Guerrieri' WHERE entry=1137; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc9='Seriadne' WHERE entry=1149; /* icon_name: Seriadne */
UPDATE locales_points_of_interest SET icon_name_loc9='Cyndra Kindwhisper' WHERE entry=1155; /* icon_name: Cyndra Kindwhisper */
UPDATE locales_points_of_interest SET icon_name_loc9='Alanna Raveneye' WHERE entry=1157; /* icon_name: Alanna Raveneye */
UPDATE locales_points_of_interest SET icon_name_loc9='Zarrin' WHERE entry=1158; /* icon_name: Zarrin */
UPDATE locales_points_of_interest SET icon_name_loc9='Byancie' WHERE entry=1159; /* icon_name: Byancie */
UPDATE locales_points_of_interest SET icon_name_loc9='Shoja\'my' WHERE entry=1166; /* icon_name: Shoja\'my */
UPDATE locales_points_of_interest SET icon_name_loc9='Thotar' WHERE entry=1167; /* icon_name: Thotar */
UPDATE locales_points_of_interest SET icon_name_loc9='Un\'Thuwa' WHERE entry=1168; /* icon_name: Un\'Thuwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Tai\'jin' WHERE entry=1169; /* icon_name: Tai\'jin */
UPDATE locales_points_of_interest SET icon_name_loc9='Rawrk' WHERE entry=1178; /* icon_name: Rawrk */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=1186; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Ambasciata dell\'Orda' WHERE entry=1188; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Orgrimmar' WHERE entry=1193; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Sayoc & Hanashi' WHERE entry=1196; /* icon_name: Sayoc & Hanashi */
UPDATE locales_points_of_interest SET icon_name_loc9='Xon\'cha' WHERE entry=1199; /* icon_name: Xon\'cha */
UPDATE locales_points_of_interest SET icon_name_loc9='Hall of Legends' WHERE entry=1201; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Orgrimmar' WHERE entry=1202; /* icon_name: Battlemasters Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione Darkbriar' WHERE entry=1207; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchemi e Pozioni di Yelmak' WHERE entry=1208; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione dello Spirito' WHERE entry=1209; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=1210; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratellanza Shadowswift' WHERE entry=1211; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc9='Enclave di Darkfire' WHERE entry=1212; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Coraggiosi' WHERE entry=1213; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=1214; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Incudine Bruciante' WHERE entry=1215; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozza del Fuoco di Borstan' WHERE entry=1216; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc9='Lavori Runici di Godan' WHERE entry=1220; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc9='Officina di Nogg' WHERE entry=1222; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc9='Sopravvivenza dei Più Adatti' WHERE entry=1223; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc9='Pesca di Lumak' WHERE entry=1224; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc9='Arboreto di Jandi' WHERE entry=1225; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=1227; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Estrazioni del Canyon Rosso' WHERE entry=1228; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=1229; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Tessili di Magar' WHERE entry=1230; /* icon_name: Magar\'s Cloth Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Sepulcra' WHERE entry=1237; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Archibald' WHERE entry=1239; /* icon_name: Archibald */
UPDATE locales_points_of_interest SET icon_name_loc9='Anya Maulray' WHERE entry=1240; /* icon_name: Anya Maulray */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Undercity' WHERE entry=1241; /* icon_name: Battlemasters Undercity */
UPDATE locales_points_of_interest SET icon_name_loc9='The Apothecarium' WHERE entry=1246; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc9='Campione Cyssa Dawnrose' WHERE entry=1263; /* icon_name: Champion Cyssa Dawnrose */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna dell\'Impiccato' WHERE entry=1268; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='Cain Firesong' WHERE entry=1271; /* icon_name: Cain Firesong */
UPDATE locales_points_of_interest SET icon_name_loc9='Rupert Boch' WHERE entry=1275; /* icon_name: Rupert Boch */
UPDATE locales_points_of_interest SET icon_name_loc9='Austil de Mon' WHERE entry=1276; /* icon_name: Austil de Mon */
UPDATE locales_points_of_interest SET icon_name_loc9='Carolai Anise' WHERE entry=1277; /* icon_name: Carolai Anise */
UPDATE locales_points_of_interest SET icon_name_loc9='Vance Undergloom' WHERE entry=1278; /* icon_name: Vance Undergloom */
UPDATE locales_points_of_interest SET icon_name_loc9='Clyde Kellen' WHERE entry=1280; /* icon_name: Clyde Kellen */
UPDATE locales_points_of_interest SET icon_name_loc9='Shelene Rhobart' WHERE entry=1283; /* icon_name: Shelene Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc9='Rand Rhobart' WHERE entry=1284; /* icon_name: Rand Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc9='Bowen Brisboise' WHERE entry=1285; /* icon_name: Bowen Brisboise */
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda di Bloodhoof Village' WHERE entry=1286; /* icon_name: Bloodhoof Village Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Seikwa' WHERE entry=1287; /* icon_name: Seikwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Yaw Sharpmane' WHERE entry=1289; /* icon_name: Yaw Sharpmane */
UPDATE locales_points_of_interest SET icon_name_loc9='Vira Younghoof' WHERE entry=1297; /* icon_name: Vira Younghoof */
UPDATE locales_points_of_interest SET icon_name_loc9='Chaw Stronghide' WHERE entry=1301; /* icon_name: Chaw Stronghide */
UPDATE locales_points_of_interest SET icon_name_loc9='Yonn Deepcut' WHERE entry=1302; /* icon_name: Yonn Deepcut */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Thunder Bluff' WHERE entry=1303; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc9='Informazioni Civiche di Thunder Bluff' WHERE entry=1305; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc9='Ansekhwa' WHERE entry=1309; /* icon_name: Ansekhwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Bulrug' WHERE entry=1310; /* icon_name: Bulrug */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Thunder Bluff' WHERE entry=1311; /* icon_name: Battlemasters Thunder Bluff */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Anziani' WHERE entry=1314; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=1315; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozze delle Visioni' WHERE entry=1317; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozze delle Visioni' WHERE entry=1318; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Spiriti' WHERE entry=1319; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=1320; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Fucina di Karn' WHERE entry=1323; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimia di Bena' WHERE entry=1324; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc9='Cucina di Aska' WHERE entry=1325; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc9='Incantatori Dawnstrider' WHERE entry=1326; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc9='Cure Spirituali' WHERE entry=1327; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc9='Esca & Attrezzatura da Pesca Mountaintop' WHERE entry=1328; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc9='Erbalismo Holistic' WHERE entry=1329; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=1331; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Geologia Stonehoof' WHERE entry=1332; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=1334; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Locandiere' WHERE entry=1335; /* icon_name: Azure Watch: Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Stalliere' WHERE entry=1337; /* icon_name: Azure Watch: Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Cacciatore' WHERE entry=1338; /* icon_name: Azure Watch: Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Mago' WHERE entry=1340; /* icon_name: Azure Watch: Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Paladino' WHERE entry=1341; /* icon_name: Azure Watch: Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Sacerdote' WHERE entry=1342; /* icon_name: Azure Watch: Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Sciamano' WHERE entry=1343; /* icon_name: Azure Watch: Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Guerriero' WHERE entry=1344; /* icon_name: Azure Watch: Warrior Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Alchimista' WHERE entry=1345; /* icon_name: Azure Watch: Alchemy Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante di Primo soccorso' WHERE entry=1351; /* icon_name: Azure Watch: First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Ammen Vale: Pescatore' WHERE entry=1352; /* icon_name: Ammen Vale: Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Erboristeria' WHERE entry=1353; /* icon_name: Azure Watch: Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc9='Azure Watch: Insegnante Minatore' WHERE entry=1357; /* icon_name: Azure Watch: Mining Trainer */
UPDATE locales_points_of_interest SET icon_name_loc9='Club Birra del Mese, Orgrimmar' WHERE entry=1715; /* icon_name: Brew of the Month Club, Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Brewfest Souvenirs' WHERE entry=1716; /* icon_name: Brewfest Souvenirs */
UPDATE locales_points_of_interest SET icon_name_loc9='Corsa dei Montoni del Brewfest' WHERE entry=1717; /* icon_name: Brewfest Ram Racing */
UPDATE locales_points_of_interest SET icon_name_loc9='Club Birra del Mese, Ironforge' WHERE entry=1718; /* icon_name: Brew of the Month Club, Ironforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimista di Orgrimmar' WHERE entry=1845; /* icon_name: Alchemist of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=1901; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Orgrimmar: ' WHERE entry=1912; /* icon_name: Orgrimmar: */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Orgrimmar' WHERE entry=8224; /* icon_name: Battlemasters Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=12627; /* icon_name: Bank of Orgrimmar */

SET NAMES 'latin1';
