-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=401 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=401 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=401 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=401 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=401 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=401 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=401 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=401 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=401 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=421 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=421 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=421 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=421 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=421 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=421 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=421 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=421 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=421 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=421 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=421 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=421 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=421 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Casa de subastas' WHERE menu_id=435 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de grifos' WHERE menu_id=435 AND id=5; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hermandad' WHERE menu_id=435 AND id=6; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cerrajero' WHERE menu_id=435 AND id=7; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=435 AND id=8; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de batalla' WHERE menu_id=435 AND id=11; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peluquero' WHERE menu_id=435 AND id=12; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc7='Lexicón de poder' WHERE menu_id=435 AND id=13; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc7='Lexicón de poder' WHERE menu_id=721 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=740 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=740 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=740 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=740 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=740 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=740 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=751 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=751 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=751 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=751 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=751 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=751 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=751 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=751 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=751 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=751 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=751 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=751 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=1942 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=1942 AND id=2; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=1942 AND id=3; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=1942 AND id=4; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=1942 AND id=5; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=1942 AND id=6; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=1942 AND id=7; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=1942 AND id=9; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=1942 AND id=10; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=1942 AND id=11; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=1942 AND id=12; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=1942 AND id=13; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=1942 AND id=15; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=1942 AND id=16; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=1949 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=1949 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=1949 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=1949 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=1949 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=1949 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=1949 AND id=6; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=1949 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=1949 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peluquero' WHERE menu_id=1951 AND id=5; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc7='Casa de subastas' WHERE menu_id=2121 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de grifos' WHERE menu_id=2121 AND id=3; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hermandad' WHERE menu_id=2121 AND id=4; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Buzón' WHERE menu_id=2121 AND id=6; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=2121 AND id=7; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de batalla' WHERE menu_id=2121 AND id=9; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peluquero' WHERE menu_id=2121 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=2144 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=2144 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=2144 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=2144 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=2144 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=2144 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=2144 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=2144 AND id=7; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=2168 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=2168 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=2168 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=2168 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=2168 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=2168 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=2168 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=2168 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=2168 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=2168 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=2168 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=2168 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=2168 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=2343 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=2343 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=2343 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=2343 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=2343 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=2351 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=2351 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=2351 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=2351 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=2351 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=2351 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=2351 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=2351 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=2351 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=2351 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Casa de subastas' WHERE menu_id=2352 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hipogrifos' WHERE menu_id=2352 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hermandad' WHERE menu_id=2352 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Buzón' WHERE menu_id=2352 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=2352 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de batalla' WHERE menu_id=2352 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Lexicón de poder' WHERE menu_id=2352 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=2847 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=2847 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=2847 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=2847 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=2847 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=2847 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=2847 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=2847 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=2847 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=2847 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=2847 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=2847 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=2847 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=2848 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=2848 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=2848 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=2848 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=2848 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=2848 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peluquero' WHERE menu_id=2849 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cerrajero' WHERE menu_id=2849 AND id=14; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc7='Casa de subastas' WHERE menu_id=3127 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc7='Banco' WHERE menu_id=3127 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc7='Posada' WHERE menu_id=3127 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=3283 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=3283 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=3283 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=3283 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=3283 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=3283 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=3283 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=3284 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=3284 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=3284 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=3284 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=3284 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=3284 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=3284 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=3284 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=3284 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=3284 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=3284 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=3284 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=3284 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=3329 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=3329 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=3329 AND id=2; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=3329 AND id=3; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=3330 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=3330 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=3330 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=3330 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=3330 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=3330 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=3330 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=3330 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=3330 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=3330 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=3330 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=3330 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=3354 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=3354 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=3354 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=3354 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=3354 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=3354 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=3355 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=3355 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=3355 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=3355 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=3355 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=3355 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=3355 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=3355 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=3355 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=3355 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=3355 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=3355 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=3355 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Banco' WHERE menu_id=3506 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de grifos' WHERE menu_id=3506 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hermandad' WHERE menu_id=3506 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Posada' WHERE menu_id=3506 AND id=3; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=3506 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=3519 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=3519 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=3519 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=3519 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=3519 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=3519 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=3519 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=3519 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=3519 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=3532 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=3532 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=3532 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=3532 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=3532 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=3532 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=3532 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=3532 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=3532 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=3532 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=3532 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=3532 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=3532 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Banco' WHERE menu_id=3533 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de grifos' WHERE menu_id=3533 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hermandad' WHERE menu_id=3533 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=3533 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=3545 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=3545 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=3545 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=3545 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=3545 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=3545 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=3545 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=3558 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=3558 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=3558 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=3558 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=3558 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=3558 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=3558 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=3558 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=3558 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=3558 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=3558 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=3558 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=3558 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=3564 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=3564 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=3564 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=3564 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=3564 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=3572 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=3572 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=3572 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=3572 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=3572 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=3572 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=3572 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=3572 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=3572 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=3572 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=3580 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Gul\'dan' WHERE menu_id=4764 AND id=0; /* option_text: Gul\'dan */
UPDATE locales_gossip_menu_option SET option_text_loc7='Kel\'Thuzad' WHERE menu_id=4764 AND id=1; /* option_text: Kel\'Thuzad */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maza' WHERE menu_id=5222 AND id=2; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc7='Bastón' WHERE menu_id=5222 AND id=4; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maza' WHERE menu_id=5262 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maza' WHERE menu_id=5268 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc7='Bastón' WHERE menu_id=5268 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maza' WHERE menu_id=5270 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maza' WHERE menu_id=5272 AND id=3; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc7='Bastón' WHERE menu_id=5274 AND id=4; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maza' WHERE menu_id=5276 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc7='Bastón' WHERE menu_id=5276 AND id=6; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de armas' WHERE menu_id=7633 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=7649 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=7649 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=7649 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=7649 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=7649 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=7649 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=7649 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=7667 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=7667 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=7667 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=7667 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=7667 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=7667 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=7667 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=7667 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=7667 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=7667 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=7667 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=7667 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=7667 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=7667 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hipogrifos' WHERE menu_id=7777 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de armas' WHERE menu_id=7777 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de batalla de arena' WHERE menu_id=7786 AND id=0; /* option_text: Arena Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=7787 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=7787 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=7787 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=7787 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=7787 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=7787 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=7787 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=7788 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=7788 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=7788 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=7788 AND id=3; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=7788 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=7788 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=7788 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=7788 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=7788 AND id=8; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=7788 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=7788 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=7788 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=7788 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=7788 AND id=13; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Posada de Ciudad de Lunargenta' WHERE menu_id=7845 AND id=0; /* option_text: Silvermoon City Inn */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hipogrifos' WHERE menu_id=8129 AND id=1; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=8137 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=8137 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=8137 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=8137 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=8137 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=8137 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=8137 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=8138 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=8138 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=8138 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=8138 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=8138 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=8138 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=8138 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=8138 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=8138 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=8138 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=8138 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=8138 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=8138 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=8138 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=8196 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=8196 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=8196 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=8196 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=8196 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=8196 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=8196 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=8205 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=8205 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=8205 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=8205 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=8205 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=8205 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=8205 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=8205 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=8205 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=8205 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=8205 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=8205 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=8205 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=8205 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Banco' WHERE menu_id=8282 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc7='Posada' WHERE menu_id=8282 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de vuelo' WHERE menu_id=8282 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Buzón' WHERE menu_id=8282 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=8282 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de batalla' WHERE menu_id=8282 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Laboratorio de alquimia' WHERE menu_id=8282 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=8326 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=8326 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=8326 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=8326 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=8326 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=8326 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=8326 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=8326 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Banco' WHERE menu_id=8357 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc7='Posada' WHERE menu_id=8357 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de vuelo' WHERE menu_id=8357 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Buzón' WHERE menu_id=8357 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=8357 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de batalla' WHERE menu_id=8357 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Laboratorio de alquimia' WHERE menu_id=8357 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=8403 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=8403 AND id=2; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=8403 AND id=3; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=8403 AND id=4; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=8403 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=8403 AND id=6; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=8403 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=8403 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Banco' WHERE menu_id=8419 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc7='Posada' WHERE menu_id=8419 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de vuelo' WHERE menu_id=8419 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Buzón' WHERE menu_id=8419 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=8419 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de batalla' WHERE menu_id=8419 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Laboratorio de alquimia' WHERE menu_id=8419 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=8424 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=8424 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=8424 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=8424 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=8424 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=8424 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=8424 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=8424 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Bastón' WHERE menu_id=8590 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maza' WHERE menu_id=8611 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc7='Bastón' WHERE menu_id=8611 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=8994 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=8994 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=8995 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=8996 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=8996 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=8997 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=8997 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=8999 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=8999 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=9000 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9001 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=9001 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9002 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=9002 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9017 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=9017 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9018 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=9018 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9025 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=9025 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9026 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Club de la Cerveza del Mes' WHERE menu_id=9026 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc7='El Lady Mehley' WHERE menu_id=9038 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9038 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9040 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='El Lady Mehley' WHERE menu_id=9041 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc7='El Lady Mehley' WHERE menu_id=9042 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9042 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='El Lady Mehley' WHERE menu_id=9043 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9043 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9073 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='La Fantasía de la Doncella' WHERE menu_id=9074 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9074 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='La Fantasía de la Doncella' WHERE menu_id=9075 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc7='La Fantasía de la Doncella' WHERE menu_id=9076 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9076 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cohete abisal X-51' WHERE menu_id=9191 AND id=0; /* option_text: X-51 Nether-Rocket */
UPDATE locales_gossip_menu_option SET option_text_loc7='Máquina de clima goblin - Prototipo 01-B' WHERE menu_id=9191 AND id=2; /* option_text: Goblin Weather Machine - Prototype 01-B */
UPDATE locales_gossip_menu_option SET option_text_loc7='Prole de hipogrifo' WHERE menu_id=9192 AND id=1; /* option_text: Hippogryph Hatchling */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tortuga de montar' WHERE menu_id=9192 AND id=2; /* option_text: Riding Turtle */
UPDATE locales_gossip_menu_option SET option_text_loc7='Fuegos artificiales morados perpetuos' WHERE menu_id=9193 AND id=1; /* option_text: Perpetual Purple Firework */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ídolo de ogro tallado' WHERE menu_id=9193 AND id=2; /* option_text: Carved Ogre Idol */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tabardo de lo arcano' WHERE menu_id=9193 AND id=3; /* option_text: Tabard of the Arcane */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tabardo de resplandor' WHERE menu_id=9193 AND id=4; /* option_text: Tabard of Brilliance */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tabardo del defensor' WHERE menu_id=9193 AND id=5; /* option_text: Tabard of the Defender */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tabardo de furia' WHERE menu_id=9193 AND id=6; /* option_text: Tabard of Fury */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tabardo de naturaleza' WHERE menu_id=9193 AND id=7; /* option_text: Tabard of Nature */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tabardo del Vacío' WHERE menu_id=9193 AND id=8; /* option_text: Tabard of the Void */
UPDATE locales_gossip_menu_option SET option_text_loc7='Caja de mascota de Landro' WHERE menu_id=9193 AND id=9; /* option_text: Landro\'s Pet Box */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cesta de merienda' WHERE menu_id=9194 AND id=0; /* option_text: Picnic Basket */
UPDATE locales_gossip_menu_option SET option_text_loc7='Diablillo en bola' WHERE menu_id=9194 AND id=2; /* option_text: Imp in a Ball */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tetera de potaje goblin' WHERE menu_id=9195 AND id=0; /* option_text: Goblin Gumbo Kettle */
UPDATE locales_gossip_menu_option SET option_text_loc7='Silla para pescar' WHERE menu_id=9195 AND id=1; /* option_text: Fishing Chair */
UPDATE locales_gossip_menu_option SET option_text_loc7='Riendas del tigre espectral' WHERE menu_id=9195 AND id=2; /* option_text: Reins of the Spectral Tiger */
UPDATE locales_gossip_menu_option SET option_text_loc7='Juego de máquina voladora de papel' WHERE menu_id=9196 AND id=0; /* option_text: Paper Flying Machine Kit */
UPDATE locales_gossip_menu_option SET option_text_loc7='Gallina cohete' WHERE menu_id=9196 AND id=1; /* option_text: Rocket Chicken */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cometa de dragón' WHERE menu_id=9196 AND id=2; /* option_text: Dragon Kite */
UPDATE locales_gossip_menu_option SET option_text_loc7='A través de El Portal Oscuro' WHERE menu_id=9197 AND id=1; /* option_text: Through the Dark Portal */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9558 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alimentos y bebidas' WHERE menu_id=9559 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc7='Senda de Illidan' WHERE menu_id=9629 AND id=0; /* option_text: Path of Illidan */
UPDATE locales_gossip_menu_option SET option_text_loc7='Comerciante de almas etéreo' WHERE menu_id=9629 AND id=2; /* option_text: Ethereal Soul-Trader */
UPDATE locales_gossip_menu_option SET option_text_loc7='G.R.A.N.A.D.A. de fiesta' WHERE menu_id=9682 AND id=0; /* option_text: Party G.R.E.N.A.D.E. */
UPDATE locales_gossip_menu_option SET option_text_loc7='La bandera de potestad' WHERE menu_id=9682 AND id=1; /* option_text: The Flag of Ownership */
UPDATE locales_gossip_menu_option SET option_text_loc7='Arena' WHERE menu_id=10043 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peluquero' WHERE menu_id=10043 AND id=3; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cerrajero' WHERE menu_id=10043 AND id=9; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc7='Distrito de Mercaderes' WHERE menu_id=10056 AND id=5; /* option_text: Trade District */
UPDATE locales_gossip_menu_option SET option_text_loc7='Lexicón de poder' WHERE menu_id=10056 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=10078 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=10078 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=10078 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=10078 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=10078 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=10078 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=10078 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=10078 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=10078 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Joyería' WHERE menu_id=10078 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=10078 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=10078 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=10078 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=10078 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Instructor de magos' WHERE menu_id=10082 AND id=3; /* option_text: Mage Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc7='Arena' WHERE menu_id=10106 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc7='Banco' WHERE menu_id=10106 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc7='Posada' WHERE menu_id=10106 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc7='Armaduras de cuero' WHERE menu_id=10170 AND id=1; /* option_text: Leather Armor */
UPDATE locales_gossip_menu_option SET option_text_loc7='Armadura de malla' WHERE menu_id=10170 AND id=2; /* option_text: Mail Armor */
UPDATE locales_gossip_menu_option SET option_text_loc7='Escudos' WHERE menu_id=10170 AND id=4; /* option_text: Shields */
UPDATE locales_gossip_menu_option SET option_text_loc7='Instructora de joyería' WHERE menu_id=10173 AND id=6; /* option_text: Jewelcrafting Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc7='Componentes' WHERE menu_id=10173 AND id=9; /* option_text: Reagents */
UPDATE locales_gossip_menu_option SET option_text_loc7='Armas' WHERE menu_id=10173 AND id=13; /* option_text: Weapons */
UPDATE locales_gossip_menu_option SET option_text_loc7='Casa de subastas' WHERE menu_id=10265 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hipogrifos' WHERE menu_id=10265 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestro de hermandad' WHERE menu_id=10265 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Buzón' WHERE menu_id=10265 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de establos' WHERE menu_id=10265 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maestra de batalla' WHERE menu_id=10265 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Lexicón de poder' WHERE menu_id=10265 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tigre balancín' WHERE menu_id=10330 AND id=0; /* option_text: Sandbox Tiger */
UPDATE locales_gossip_menu_option SET option_text_loc7='Camisa morada épica' WHERE menu_id=10330 AND id=1; /* option_text: Epic Purple Shirt */
UPDATE locales_gossip_menu_option SET option_text_loc7='Expositor para espadas de gomaespuma' WHERE menu_id=10330 AND id=2; /* option_text: Foam Sword Rack */
UPDATE locales_gossip_menu_option SET option_text_loc7='Senda de Cenarius' WHERE menu_id=10533 AND id=0; /* option_text: Path of Cenarius */
UPDATE locales_gossip_menu_option SET option_text_loc7='Piñata ogra' WHERE menu_id=10533 AND id=1; /* option_text: Ogre Pinata */
UPDATE locales_gossip_menu_option SET option_text_loc7='Gallo mágico' WHERE menu_id=10533 AND id=2; /* option_text: Magic Rooster */
UPDATE locales_gossip_menu_option SET option_text_loc7='Tundra Boreal' WHERE menu_id=10668 AND id=0; /* option_text: Borean Tundra */
UPDATE locales_gossip_menu_option SET option_text_loc7='Fiordo Aquilonal' WHERE menu_id=10668 AND id=1; /* option_text: Howling Fjord */
UPDATE locales_gossip_menu_option SET option_text_loc7='Alquimia' WHERE menu_id=10767 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herrería' WHERE menu_id=10767 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=10767 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Encantamiento' WHERE menu_id=10767 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc7='Ingeniería' WHERE menu_id=10767 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc7='Primeros auxilios' WHERE menu_id=10767 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=10767 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=10767 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=10767 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peletería' WHERE menu_id=10767 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Minería y joyería' WHERE menu_id=10767 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc7='Desuello' WHERE menu_id=10767 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sastrería' WHERE menu_id=10767 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc7='Maga' WHERE menu_id=10768 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc7='Paladín' WHERE menu_id=10768 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=10768 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=10768 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=10768 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=10768 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peluquero' WHERE menu_id=10769 AND id=2; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cerrajero' WHERE menu_id=10769 AND id=7; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cometa colmillarr' WHERE menu_id=10810 AND id=1; /* option_text: Tuskarr Kite */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cachorro de tigre espectral' WHERE menu_id=10810 AND id=2; /* option_text: Spectral Tiger Cub */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sala de los Campeones' WHERE menu_id=11845 AND id=0; /* option_text: Champions\' Hall */
UPDATE locales_gossip_menu_option SET option_text_loc7='El Parque' WHERE menu_id=11845 AND id=2; /* option_text: The Park */
UPDATE locales_gossip_menu_option SET option_text_loc7='Castillo de Ventormenta' WHERE menu_id=11845 AND id=5; /* option_text: Stormwind Keep */
UPDATE locales_gossip_menu_option SET option_text_loc7='Casa de subastas' WHERE menu_id=11848 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc7='Criadora de caballos' WHERE menu_id=11848 AND id=4; /* option_text: Horse Breeder */
UPDATE locales_gossip_menu_option SET option_text_loc7='Peluquero' WHERE menu_id=11969 AND id=5; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc7='Druida' WHERE menu_id=11976 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cazadora' WHERE menu_id=11976 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc7='Sacerdotisa' WHERE menu_id=11976 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pícara' WHERE menu_id=11976 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc7='Chamán' WHERE menu_id=11976 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc7='Brujo' WHERE menu_id=11976 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc7='Guerrero' WHERE menu_id=11976 AND id=7; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc7='Cocina' WHERE menu_id=11977 AND id=0; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc7='Herboristería' WHERE menu_id=11977 AND id=1; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc7='Inscripción' WHERE menu_id=11977 AND id=2; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pesca' WHERE menu_id=11977 AND id=3; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc7='Pertrechos' WHERE menu_id=11978 AND id=0; /* option_text: General Goods */
UPDATE locales_gossip_menu_option SET option_text_loc7='Venenos y componentes' WHERE menu_id=11978 AND id=1; /* option_text: Poisons & Reagents */
UPDATE locales_gossip_menu_option SET option_text_loc7='Suministros comerciales' WHERE menu_id=11978 AND id=3; /* option_text: Trade Supplies */
UPDATE locales_gossip_menu_option SET option_text_loc7='Valle de la Fuerza' WHERE menu_id=12637 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc7='Valle del Honor' WHERE menu_id=12637 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc7='Valle de la Fuerza' WHERE menu_id=12638 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc7='Valle del Honor' WHERE menu_id=12638 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc7='Valle de la Fuerza' WHERE menu_id=12639 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc7='Valle del Honor' WHERE menu_id=12639 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc7='Dracohalcón Amani' WHERE menu_id=12785 AND id=2; /* option_text: Amani Dragonhawk */

SET NAMES 'latin1';
