-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc6='Posada Orgullo de León' WHERE entry=1; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc6='Zaldimar Wefhellt' WHERE entry=2; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc6='Hermano Wilhelm' WHERE entry=3; /* icon_name: Brother Wilhelm */
UPDATE locales_points_of_interest SET icon_name_loc6='Sacerdotisa Josetta' WHERE entry=4; /* icon_name: Priestess Josetta */
UPDATE locales_points_of_interest SET icon_name_loc6='Keryn Sylvius' WHERE entry=5; /* icon_name: Keryn Sylvius */
UPDATE locales_points_of_interest SET icon_name_loc6='Maximillian Crowe' WHERE entry=6; /* icon_name: Maximillian Crowe */
UPDATE locales_points_of_interest SET icon_name_loc6='Lyria Du Lac' WHERE entry=7; /* icon_name: Lyria Du Lac */
UPDATE locales_points_of_interest SET icon_name_loc6='Alquimista Mallory' WHERE entry=8; /* icon_name: Alchemist Mallory */
UPDATE locales_points_of_interest SET icon_name_loc6='Herrero Argus' WHERE entry=9; /* icon_name: Smith Argus */
UPDATE locales_points_of_interest SET icon_name_loc6='Tomas' WHERE entry=10; /* icon_name: Tomas */
UPDATE locales_points_of_interest SET icon_name_loc6='Michelle Belle' WHERE entry=11; /* icon_name: Michelle Belle */
UPDATE locales_points_of_interest SET icon_name_loc6='Lee Moreno' WHERE entry=12; /* icon_name: Lee Brown */
UPDATE locales_points_of_interest SET icon_name_loc6='Adele Fielder' WHERE entry=14; /* icon_name: Adele Fielder */
UPDATE locales_points_of_interest SET icon_name_loc6='Helene Desollapelambres' WHERE entry=15; /* icon_name: Helene Peltskinner */
UPDATE locales_points_of_interest SET icon_name_loc6='Eldrin' WHERE entry=16; /* icon_name: Eldrin */
UPDATE locales_points_of_interest SET icon_name_loc6='Erma' WHERE entry=17; /* icon_name: Erma */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas: Ventormenta' WHERE entry=18; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Puerto de Ventormenta' WHERE entry=20; /* icon_name: Stormwind Harbor */
UPDATE locales_points_of_interest SET icon_name_loc6='La Rosa Áurea' WHERE entry=22; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc6='Centro del Viajero de Ventormenta' WHERE entry=24; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc6='Jenova Petrescudo' WHERE entry=26; /* icon_name: Jenova Stoneshield */
UPDATE locales_points_of_interest SET icon_name_loc6='Woo Ping' WHERE entry=27; /* icon_name: Woo Ping */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Campeones' WHERE entry=28; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc6='El Parque' WHERE entry=32; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc6='Sagrario del Mago' WHERE entry=34; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc6='Catedral de la Luz' WHERE entry=35; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc6='Clarividente Umbrua' WHERE entry=37; /* icon_name: Farseer Umbrua */
UPDATE locales_points_of_interest SET icon_name_loc6='El Cordero Degollado' WHERE entry=38; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc6='El Rincón del Alquimista' WHERE entry=40; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc6='Therum Forjahonda' WHERE entry=41; /* icon_name: Therum Deepforge */
UPDATE locales_points_of_interest SET icon_name_loc6='El Cerdo Borracho' WHERE entry=42; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc6='Lucan Cordell' WHERE entry=43; /* icon_name: Lucan Cordell */
UPDATE locales_points_of_interest SET icon_name_loc6='Lilliam Chispeje' WHERE entry=44; /* icon_name: Lilliam Sparkspindle */
UPDATE locales_points_of_interest SET icon_name_loc6='Shaina Fuller' WHERE entry=45; /* icon_name: Shaina Fuller */
UPDATE locales_points_of_interest SET icon_name_loc6='Arnold Leland' WHERE entry=46; /* icon_name: Arnold Leland */
UPDATE locales_points_of_interest SET icon_name_loc6='La Piel Protectora' WHERE entry=47; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc6='Gelman Petramano' WHERE entry=48; /* icon_name: Gelman Stonehand */
UPDATE locales_points_of_interest SET icon_name_loc6='Telas de Duncan' WHERE entry=49; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas de Forjaz' WHERE entry=50; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc6='Tranvía Subterráneo' WHERE entry=52; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc6='Centro del Viajero de Forjaz' WHERE entry=54; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc6='Ulbrek Manofuego' WHERE entry=57; /* icon_name: Ulbrek Firehand */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de Armas' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Misterios' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc6='Pociones y cócteles de Burbubaya' WHERE entry=66; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc6='La Gran Fundición' WHERE entry=67; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc6='La Tetera de Bronce' WHERE entry=68; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc6='Arcanería Cardopelusa' WHERE entry=69; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc6='Médico de Forjaz' WHERE entry=70; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc6='El Pescador Nómada' WHERE entry=71; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc6='Artículos de Cuero Bueneje' WHERE entry=73; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc6='Sastrería Petrocejas' WHERE entry=75; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc6='Destilería Cebatruenos' WHERE entry=76; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc6='Shelby Petrepiedra' WHERE entry=77; /* icon_name: Shelby Stoneflint */
UPDATE locales_points_of_interest SET icon_name_loc6='Grif Corazón Salvaje' WHERE entry=78; /* icon_name: Grif Wildheart */
UPDATE locales_points_of_interest SET icon_name_loc6='Magis Chispamanto' WHERE entry=79; /* icon_name: Magis Sparkmantle */
UPDATE locales_points_of_interest SET icon_name_loc6='Azar Martillopujante' WHERE entry=80; /* icon_name: Azar Stronghammer */
UPDATE locales_points_of_interest SET icon_name_loc6='Maxan Anvol' WHERE entry=81; /* icon_name: Maxan Anvol */
UPDATE locales_points_of_interest SET icon_name_loc6='Hogral Bakkan' WHERE entry=82; /* icon_name: Hogral Bakkan */
UPDATE locales_points_of_interest SET icon_name_loc6='Gimrizz Molaro' WHERE entry=83; /* icon_name: Gimrizz Shadowcog */
UPDATE locales_points_of_interest SET icon_name_loc6='Granis Hachaveloz' WHERE entry=84; /* icon_name: Granis Swiftaxe */
UPDATE locales_points_of_interest SET icon_name_loc6='Tognus Fuegosílex' WHERE entry=85; /* icon_name: Tognus Flintfire */
UPDATE locales_points_of_interest SET icon_name_loc6='Gremlock Pilsnor' WHERE entry=86; /* icon_name: Gremlock Pilsnor */
UPDATE locales_points_of_interest SET icon_name_loc6='Thamner Pol' WHERE entry=87; /* icon_name: Thamner Pol */
UPDATE locales_points_of_interest SET icon_name_loc6='Paxton Ganter' WHERE entry=88; /* icon_name: Paxton Ganter */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas: Darnassus' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Alassin' WHERE entry=95; /* icon_name: Alassin */
UPDATE locales_points_of_interest SET icon_name_loc6='Ilyenia Fuegolunar' WHERE entry=96; /* icon_name: Ilyenia Moonfire */
UPDATE locales_points_of_interest SET icon_name_loc6='Bancal del Guerrero' WHERE entry=101; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc6='Seriadne' WHERE entry=112; /* icon_name: Seriadne */
UPDATE locales_points_of_interest SET icon_name_loc6='Kal' WHERE entry=113; /* icon_name: Kal */
UPDATE locales_points_of_interest SET icon_name_loc6='Dazalar' WHERE entry=114; /* icon_name: Dazalar */
UPDATE locales_points_of_interest SET icon_name_loc6='Laurna Luzdelalba' WHERE entry=115; /* icon_name: Laurna Morninglight */
UPDATE locales_points_of_interest SET icon_name_loc6='Jannok Brisón' WHERE entry=116; /* icon_name: Jannok Breezesong */
UPDATE locales_points_of_interest SET icon_name_loc6='Kyra Espada del Viento' WHERE entry=117; /* icon_name: Kyra Windblade */
UPDATE locales_points_of_interest SET icon_name_loc6='Cyndra Suavesusurro' WHERE entry=118; /* icon_name: Cyndra Kindwhisper */
UPDATE locales_points_of_interest SET icon_name_loc6='Zarrin' WHERE entry=119; /* icon_name: Zarrin */
UPDATE locales_points_of_interest SET icon_name_loc6='Alanna Cuervojo' WHERE entry=120; /* icon_name: Alanna Raveneye */
UPDATE locales_points_of_interest SET icon_name_loc6='Byancie' WHERE entry=121; /* icon_name: Byancie */
UPDATE locales_points_of_interest SET icon_name_loc6='Malorne Filohoja' WHERE entry=122; /* icon_name: Malorne Bladeleaf */
UPDATE locales_points_of_interest SET icon_name_loc6='Nadyia Tejecrín' WHERE entry=123; /* icon_name: Nadyia Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc6='Radnaal Tejecrín' WHERE entry=124; /* icon_name: Radnaal Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc6='Nadyia Tejecrín' WHERE entry=125; /* icon_name: Nadyia Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc6='Pozo de Dalaran' WHERE entry=128; /* icon_name: Dalaran Well */
UPDATE locales_points_of_interest SET icon_name_loc6='Centro de visitantes de Dalaran' WHERE entry=135; /* icon_name: Dalaran Visitor Center */
UPDATE locales_points_of_interest SET icon_name_loc6='Banco de Orgrimmar' WHERE entry=176; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc6='Embajada de la Horda' WHERE entry=178; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas de Orgrimmar' WHERE entry=181; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Xon\'cha' WHERE entry=185; /* icon_name: Xon\'cha */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de las Leyendas' WHERE entry=186; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc6='Templo de la Luna' WHERE entry=267; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc6='Herborista Pomarrosa' WHERE entry=269; /* icon_name: Herbalist Pomeroy */
UPDATE locales_points_of_interest SET icon_name_loc6='Banco de Cima del Trueno' WHERE entry=275; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc6='Información al Ciudadano de Cima del Trueno' WHERE entry=277; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc6='Ansekhwa' WHERE entry=281; /* icon_name: Ansekhwa */
UPDATE locales_points_of_interest SET icon_name_loc6='Bulrug' WHERE entry=282; /* icon_name: Bulrug */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Ancestros' WHERE entry=285; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc6='Recinto de los Cazadores' WHERE entry=286; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc6='Pozas de las Visiones' WHERE entry=287; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Espíritus' WHERE entry=288; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc6='La Alquimia de Bena' WHERE entry=289; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc6='Herrería de Karn' WHERE entry=290; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc6='La Cocina de Aska' WHERE entry=291; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc6='Encantadores Caminalba' WHERE entry=292; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc6='Curación Espiritual' WHERE entry=293; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc6='Anzuelos y Aparejos La Cumbre' WHERE entry=294; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc6='Herboristería Holística' WHERE entry=295; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc6='Armeros de Cima del Trueno' WHERE entry=297; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc6='Geólogos Pezuña Pétrea' WHERE entry=298; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc6='Mooranta' WHERE entry=299; /* icon_name: Mooranta */
UPDATE locales_points_of_interest SET icon_name_loc6='Cabaña de Brezo' WHERE entry=301; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc6='Recinto de los Espíritus' WHERE entry=302; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc6='Fortaleza de Thrall' WHERE entry=303; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc6='Hermandad Sombrágil' WHERE entry=304; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc6='Enclave Fuego Oscuro' WHERE entry=305; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc6='Bastión de los Valientes' WHERE entry=306; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc6='Alquimia y pociones de Yelmak' WHERE entry=307; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc6='El Yunque Ardiente' WHERE entry=308; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc6='Fosa de lava de Borstan' WHERE entry=309; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc6='Creaciones rúnicas de Godan' WHERE entry=310; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc6='Rincón de la Maquinaria de Nogg' WHERE entry=311; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc6='Supervivencia del más fuerte' WHERE entry=312; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc6='Aparejos Lumak' WHERE entry=313; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc6='Arboreto de Jandi' WHERE entry=314; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc6='Mina del Cañón Rojo' WHERE entry=315; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc6='Peleteros de piel de kodo' WHERE entry=316; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc6='Indumentarias Magar' WHERE entry=317; /* icon_name: Magar\'s Cloth Goods */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas: Entrañas' WHERE entry=318; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Anya Maulray' WHERE entry=327; /* icon_name: Anya Maulray */
UPDATE locales_points_of_interest SET icon_name_loc6='Archibald' WHERE entry=328; /* icon_name: Archibald */
UPDATE locales_points_of_interest SET icon_name_loc6='Campeona Cyssa Rosalba' WHERE entry=330; /* icon_name: Champion Cyssa Dawnrose */
UPDATE locales_points_of_interest SET icon_name_loc6='El Apothecarium' WHERE entry=336; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc6='Plaza Alalcón, instructor de paladines' WHERE entry=387; /* icon_name: Falconwing Square, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc6='Artilugios de Muello Saltarín' WHERE entry=401; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc6='Yarr Martillal' WHERE entry=402; /* icon_name: Yarr Hammerstone */
UPDATE locales_points_of_interest SET icon_name_loc6='Shoja\'my' WHERE entry=404; /* icon_name: Shoja\'my */
UPDATE locales_points_of_interest SET icon_name_loc6='Thotar' WHERE entry=405; /* icon_name: Thotar */
UPDATE locales_points_of_interest SET icon_name_loc6='Un\'Thuwa' WHERE entry=406; /* icon_name: Un\'Thuwa */
UPDATE locales_points_of_interest SET icon_name_loc6='Tai\'jin' WHERE entry=407; /* icon_name: Tai\'jin */
UPDATE locales_points_of_interest SET icon_name_loc6='Kaplak' WHERE entry=408; /* icon_name: Kaplak */
UPDATE locales_points_of_interest SET icon_name_loc6='Swart' WHERE entry=409; /* icon_name: Swart */
UPDATE locales_points_of_interest SET icon_name_loc6='Dhugru Ansiagore' WHERE entry=410; /* icon_name: Dhugru Gorelust */
UPDATE locales_points_of_interest SET icon_name_loc6='Tarshaw Marcauna' WHERE entry=411; /* icon_name: Tarshaw Jaggedscar */
UPDATE locales_points_of_interest SET icon_name_loc6='Miao\'zan' WHERE entry=412; /* icon_name: Miao\'zan */
UPDATE locales_points_of_interest SET icon_name_loc6='Dwukk' WHERE entry=413; /* icon_name: Dwukk */
UPDATE locales_points_of_interest SET icon_name_loc6='Mukdrak' WHERE entry=414; /* icon_name: Mukdrak */
UPDATE locales_points_of_interest SET icon_name_loc6='Rawrk' WHERE entry=415; /* icon_name: Rawrk */
UPDATE locales_points_of_interest SET icon_name_loc6='Lau\'Tiki' WHERE entry=416; /* icon_name: Lau\'Tiki */
UPDATE locales_points_of_interest SET icon_name_loc6='Mishiki' WHERE entry=417; /* icon_name: Mishiki */
UPDATE locales_points_of_interest SET icon_name_loc6='Krunn' WHERE entry=418; /* icon_name: Krunn */
UPDATE locales_points_of_interest SET icon_name_loc6='Seikwa' WHERE entry=420; /* icon_name: Seikwa */
UPDATE locales_points_of_interest SET icon_name_loc6='Gennia Tótem de Runa' WHERE entry=421; /* icon_name: Gennia Runetotem */
UPDATE locales_points_of_interest SET icon_name_loc6='Yaw Crinafilada' WHERE entry=422; /* icon_name: Yaw Sharpmane */
UPDATE locales_points_of_interest SET icon_name_loc6='Narm Cazacielo' WHERE entry=423; /* icon_name: Narm Skychaser */
UPDATE locales_points_of_interest SET icon_name_loc6='Krang Pezuña Pétrea' WHERE entry=424; /* icon_name: Krang Stonehoof */
UPDATE locales_points_of_interest SET icon_name_loc6='Pyall Trancosilencio' WHERE entry=425; /* icon_name: Pyall Silentstride */
UPDATE locales_points_of_interest SET icon_name_loc6='Vira Pezuña Joven' WHERE entry=426; /* icon_name: Vira Younghoof */
UPDATE locales_points_of_interest SET icon_name_loc6='Uthan Aguaserena' WHERE entry=427; /* icon_name: Uthan Stillwater */
UPDATE locales_points_of_interest SET icon_name_loc6='Chaw Pellejofuerte' WHERE entry=428; /* icon_name: Chaw Stronghide */
UPDATE locales_points_of_interest SET icon_name_loc6='Yonn Corte Profundo' WHERE entry=429; /* icon_name: Yonn Deepcut */
UPDATE locales_points_of_interest SET icon_name_loc6='Cain Pirosón' WHERE entry=433; /* icon_name: Cain Firesong */
UPDATE locales_points_of_interest SET icon_name_loc6='Clérigo oscuro Beryl' WHERE entry=434; /* icon_name: Dark Cleric Beryl */
UPDATE locales_points_of_interest SET icon_name_loc6='Marion Call' WHERE entry=435; /* icon_name: Marion Call */
UPDATE locales_points_of_interest SET icon_name_loc6='Rupert Boch' WHERE entry=436; /* icon_name: Rupert Boch */
UPDATE locales_points_of_interest SET icon_name_loc6='Austil de Mon' WHERE entry=437; /* icon_name: Austil de Mon */
UPDATE locales_points_of_interest SET icon_name_loc6='Carolai Anise' WHERE entry=438; /* icon_name: Carolai Anise */
UPDATE locales_points_of_interest SET icon_name_loc6='Vance Bajopenumbra' WHERE entry=439; /* icon_name: Vance Undergloom */
UPDATE locales_points_of_interest SET icon_name_loc6='Enfermera Neela' WHERE entry=440; /* icon_name: Nurse Neela */
UPDATE locales_points_of_interest SET icon_name_loc6='Clyde Kellen' WHERE entry=441; /* icon_name: Clyde Kellen */
UPDATE locales_points_of_interest SET icon_name_loc6='Faruza' WHERE entry=442; /* icon_name: Faruza */
UPDATE locales_points_of_interest SET icon_name_loc6='Shelene Rhobart' WHERE entry=443; /* icon_name: Shelene Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc6='Rand Rhobart' WHERE entry=444; /* icon_name: Rand Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc6='Bowen Brisboise' WHERE entry=445; /* icon_name: Bowen Brisboise */
UPDATE locales_points_of_interest SET icon_name_loc6='Mesón La Horca' WHERE entry=446; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc6='Morganus' WHERE entry=447; /* icon_name: Morganus */
UPDATE locales_points_of_interest SET icon_name_loc6='Mago de Theramore' WHERE entry=471; /* icon_name: Theramore Mage */
UPDATE locales_points_of_interest SET icon_name_loc6='Posada Orgullo de León' WHERE entry=1000; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc6='Erma' WHERE entry=1001; /* icon_name: Erma */
UPDATE locales_points_of_interest SET icon_name_loc6='Zaldimar Wefhellt' WHERE entry=1002; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc6='Hermano Wilhelm' WHERE entry=1003; /* icon_name: Brother Wilhelm */
UPDATE locales_points_of_interest SET icon_name_loc6='Sacerdotisa Josetta' WHERE entry=1004; /* icon_name: Priestess Josetta */
UPDATE locales_points_of_interest SET icon_name_loc6='Keryn Sylvius' WHERE entry=1005; /* icon_name: Keryn Sylvius */
UPDATE locales_points_of_interest SET icon_name_loc6='Maximillian Crowe' WHERE entry=1006; /* icon_name: Maximillian Crowe */
UPDATE locales_points_of_interest SET icon_name_loc6='Lyria Du Lac' WHERE entry=1007; /* icon_name: Lyria Du Lac */
UPDATE locales_points_of_interest SET icon_name_loc6='Alquimista Mallory' WHERE entry=1008; /* icon_name: Alchemist Mallory */
UPDATE locales_points_of_interest SET icon_name_loc6='Herrero Argus' WHERE entry=1009; /* icon_name: Smith Argus */
UPDATE locales_points_of_interest SET icon_name_loc6='Tomas' WHERE entry=1010; /* icon_name: Tomas */
UPDATE locales_points_of_interest SET icon_name_loc6='Michelle Belle' WHERE entry=1011; /* icon_name: Michelle Belle */
UPDATE locales_points_of_interest SET icon_name_loc6='Lee Moreno' WHERE entry=1012; /* icon_name: Lee Brown */
UPDATE locales_points_of_interest SET icon_name_loc6='Lee Moreno' WHERE entry=1013; /* icon_name: Lee Brown */
UPDATE locales_points_of_interest SET icon_name_loc6='Herborista Pomarrosa' WHERE entry=1016; /* icon_name: Herbalist Pomeroy */
UPDATE locales_points_of_interest SET icon_name_loc6='Adele Fielder' WHERE entry=1017; /* icon_name: Adele Fielder */
UPDATE locales_points_of_interest SET icon_name_loc6='Helene Desollapelambres' WHERE entry=1018; /* icon_name: Helene Peltskinner */
UPDATE locales_points_of_interest SET icon_name_loc6='Eldrin' WHERE entry=1019; /* icon_name: Eldrin */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas: Ventormenta' WHERE entry=1020; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Puerto de Ventormenta' WHERE entry=1023; /* icon_name: Stormwind Harbor */
UPDATE locales_points_of_interest SET icon_name_loc6='La Rosa Áurea' WHERE entry=1026; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc6='Centro del Viajero de Ventormenta' WHERE entry=1028; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc6='Jenova Petrescudo' WHERE entry=1030; /* icon_name: Jenova Stoneshield */
UPDATE locales_points_of_interest SET icon_name_loc6='Woo Ping' WHERE entry=1031; /* icon_name: Woo Ping */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Campeones' WHERE entry=1032; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc6='El Parque' WHERE entry=1036; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc6='Sagrario del Mago' WHERE entry=1038; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc6='Catedral de la Luz' WHERE entry=1039; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc6='Catedral de la Luz' WHERE entry=1040; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc6='Clarividente Umbrua' WHERE entry=1042; /* icon_name: Farseer Umbrua */
UPDATE locales_points_of_interest SET icon_name_loc6='El Cordero Degollado' WHERE entry=1043; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc6='El Rincón del Alquimista' WHERE entry=1045; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc6='Therum Forjahonda' WHERE entry=1046; /* icon_name: Therum Deepforge */
UPDATE locales_points_of_interest SET icon_name_loc6='El Cerdo Borracho' WHERE entry=1048; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc6='Lucan Cordell' WHERE entry=1049; /* icon_name: Lucan Cordell */
UPDATE locales_points_of_interest SET icon_name_loc6='Lilliam Chispeje' WHERE entry=1050; /* icon_name: Lilliam Sparkspindle */
UPDATE locales_points_of_interest SET icon_name_loc6='Shaina Fuller' WHERE entry=1051; /* icon_name: Shaina Fuller */
UPDATE locales_points_of_interest SET icon_name_loc6='Arnold Leland' WHERE entry=1052; /* icon_name: Arnold Leland */
UPDATE locales_points_of_interest SET icon_name_loc6='El Rincón del Alquimista' WHERE entry=1053; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc6='La Piel Protectora' WHERE entry=1055; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc6='Gelman Petramano' WHERE entry=1056; /* icon_name: Gelman Stonehand */
UPDATE locales_points_of_interest SET icon_name_loc6='La Piel Protectora' WHERE entry=1057; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc6='Telas de Duncan' WHERE entry=1058; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas de Forjaz' WHERE entry=1059; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc6='Centro del Viajero de Forjaz' WHERE entry=1066; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc6='Ulbrek Manofuego' WHERE entry=1071; /* icon_name: Ulbrek Firehand */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de Armas' WHERE entry=1077; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Misterios' WHERE entry=1078; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Misterios' WHERE entry=1079; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc6='La Tetera de Bronce' WHERE entry=1080; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de Armas' WHERE entry=1085; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc6='Pociones y cócteles de Burbubaya' WHERE entry=1087; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc6='La Gran Fundición' WHERE entry=1088; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc6='Tranvía Subterráneo' WHERE entry=1089; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc6='Arcanería Cardopelusa' WHERE entry=1090; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc6='Artilugios de Muello Saltarín' WHERE entry=1092; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc6='Médico de Forjaz' WHERE entry=1093; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc6='El Pescador Nómada' WHERE entry=1094; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc6='Médico de Forjaz' WHERE entry=1095; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc6='Artículos de Cuero Bueneje' WHERE entry=1098; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc6='Artículos de Cuero Bueneje' WHERE entry=1100; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc6='Sastrería Petrocejas' WHERE entry=1101; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc6='Destilería Cebatruenos' WHERE entry=1102; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc6='Shelby Petrepiedra' WHERE entry=1106; /* icon_name: Shelby Stoneflint */
UPDATE locales_points_of_interest SET icon_name_loc6='Grif Corazón Salvaje' WHERE entry=1107; /* icon_name: Grif Wildheart */
UPDATE locales_points_of_interest SET icon_name_loc6='Azar Martillopujante' WHERE entry=1109; /* icon_name: Azar Stronghammer */
UPDATE locales_points_of_interest SET icon_name_loc6='Magis Chispamanto' WHERE entry=1110; /* icon_name: Magis Sparkmantle */
UPDATE locales_points_of_interest SET icon_name_loc6='Maxan Anvol' WHERE entry=1111; /* icon_name: Maxan Anvol */
UPDATE locales_points_of_interest SET icon_name_loc6='Hogral Bakkan' WHERE entry=1112; /* icon_name: Hogral Bakkan */
UPDATE locales_points_of_interest SET icon_name_loc6='Gimrizz Molaro' WHERE entry=1113; /* icon_name: Gimrizz Shadowcog */
UPDATE locales_points_of_interest SET icon_name_loc6='Granis Hachaveloz' WHERE entry=1114; /* icon_name: Granis Swiftaxe */
UPDATE locales_points_of_interest SET icon_name_loc6='Tognus Fuegosílex' WHERE entry=1115; /* icon_name: Tognus Flintfire */
UPDATE locales_points_of_interest SET icon_name_loc6='Gremlock Pilsnor' WHERE entry=1116; /* icon_name: Gremlock Pilsnor */
UPDATE locales_points_of_interest SET icon_name_loc6='Thamner Pol' WHERE entry=1118; /* icon_name: Thamner Pol */
UPDATE locales_points_of_interest SET icon_name_loc6='Paxton Ganter' WHERE entry=1119; /* icon_name: Paxton Ganter */
UPDATE locales_points_of_interest SET icon_name_loc6='Yarr Martillal' WHERE entry=1122; /* icon_name: Yarr Hammerstone */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas: Darnassus' WHERE entry=1123; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Aldea Rut\'theran' WHERE entry=1125; /* icon_name: Rut\'theran Village */
UPDATE locales_points_of_interest SET icon_name_loc6='Alassin' WHERE entry=1130; /* icon_name: Alassin */
UPDATE locales_points_of_interest SET icon_name_loc6='Ilyenia Fuegolunar' WHERE entry=1131; /* icon_name: Ilyenia Moonfire */
UPDATE locales_points_of_interest SET icon_name_loc6='Templo de la Luna' WHERE entry=1135; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc6='Bancal del Guerrero' WHERE entry=1137; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc6='Seriadne' WHERE entry=1149; /* icon_name: Seriadne */
UPDATE locales_points_of_interest SET icon_name_loc6='Kal' WHERE entry=1150; /* icon_name: Kal */
UPDATE locales_points_of_interest SET icon_name_loc6='Dazalar' WHERE entry=1151; /* icon_name: Dazalar */
UPDATE locales_points_of_interest SET icon_name_loc6='Laurna Luzdelalba' WHERE entry=1152; /* icon_name: Laurna Morninglight */
UPDATE locales_points_of_interest SET icon_name_loc6='Jannok Brisón' WHERE entry=1153; /* icon_name: Jannok Breezesong */
UPDATE locales_points_of_interest SET icon_name_loc6='Kyra Espada del Viento' WHERE entry=1154; /* icon_name: Kyra Windblade */
UPDATE locales_points_of_interest SET icon_name_loc6='Cyndra Suavesusurro' WHERE entry=1155; /* icon_name: Cyndra Kindwhisper */
UPDATE locales_points_of_interest SET icon_name_loc6='Alanna Cuervojo' WHERE entry=1157; /* icon_name: Alanna Raveneye */
UPDATE locales_points_of_interest SET icon_name_loc6='Zarrin' WHERE entry=1158; /* icon_name: Zarrin */
UPDATE locales_points_of_interest SET icon_name_loc6='Byancie' WHERE entry=1159; /* icon_name: Byancie */
UPDATE locales_points_of_interest SET icon_name_loc6='Malorne Filohoja' WHERE entry=1161; /* icon_name: Malorne Bladeleaf */
UPDATE locales_points_of_interest SET icon_name_loc6='Nadyia Tejecrín' WHERE entry=1163; /* icon_name: Nadyia Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc6='Radnaal Tejecrín' WHERE entry=1164; /* icon_name: Radnaal Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc6='Shoja\'my' WHERE entry=1166; /* icon_name: Shoja\'my */
UPDATE locales_points_of_interest SET icon_name_loc6='Thotar' WHERE entry=1167; /* icon_name: Thotar */
UPDATE locales_points_of_interest SET icon_name_loc6='Un\'Thuwa' WHERE entry=1168; /* icon_name: Un\'Thuwa */
UPDATE locales_points_of_interest SET icon_name_loc6='Tai\'jin' WHERE entry=1169; /* icon_name: Tai\'jin */
UPDATE locales_points_of_interest SET icon_name_loc6='Kaplak' WHERE entry=1171; /* icon_name: Kaplak */
UPDATE locales_points_of_interest SET icon_name_loc6='Swart' WHERE entry=1172; /* icon_name: Swart */
UPDATE locales_points_of_interest SET icon_name_loc6='Dhugru Ansiagore' WHERE entry=1173; /* icon_name: Dhugru Gorelust */
UPDATE locales_points_of_interest SET icon_name_loc6='Tarshaw Marcauna' WHERE entry=1174; /* icon_name: Tarshaw Jaggedscar */
UPDATE locales_points_of_interest SET icon_name_loc6='Miao\'zan' WHERE entry=1175; /* icon_name: Miao\'zan */
UPDATE locales_points_of_interest SET icon_name_loc6='Dwukk' WHERE entry=1176; /* icon_name: Dwukk */
UPDATE locales_points_of_interest SET icon_name_loc6='Mukdrak' WHERE entry=1177; /* icon_name: Mukdrak */
UPDATE locales_points_of_interest SET icon_name_loc6='Rawrk' WHERE entry=1178; /* icon_name: Rawrk */
UPDATE locales_points_of_interest SET icon_name_loc6='Lau\'Tiki' WHERE entry=1179; /* icon_name: Lau\'Tiki */
UPDATE locales_points_of_interest SET icon_name_loc6='Krunn' WHERE entry=1184; /* icon_name: Krunn */
UPDATE locales_points_of_interest SET icon_name_loc6='Mishiki' WHERE entry=1185; /* icon_name: Mishiki */
UPDATE locales_points_of_interest SET icon_name_loc6='Banco de Orgrimmar' WHERE entry=1186; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc6='Embajada de la Horda' WHERE entry=1188; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas de Orgrimmar' WHERE entry=1193; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Xon\'cha' WHERE entry=1199; /* icon_name: Xon\'cha */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de las Leyendas' WHERE entry=1201; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc6='Cabaña de Brezo' WHERE entry=1207; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc6='Alquimia y pociones de Yelmak' WHERE entry=1208; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc6='Recinto de los Espíritus' WHERE entry=1209; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc6='Fortaleza de Thrall' WHERE entry=1210; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc6='Hermandad Sombrágil' WHERE entry=1211; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc6='Enclave Fuego Oscuro' WHERE entry=1212; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc6='Bastión de los Valientes' WHERE entry=1213; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc6='Fortaleza de Thrall' WHERE entry=1214; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc6='El Yunque Ardiente' WHERE entry=1215; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc6='Fosa de lava de Borstan' WHERE entry=1216; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc6='Creaciones rúnicas de Godan' WHERE entry=1220; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc6='Rincón de la Maquinaria de Nogg' WHERE entry=1222; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc6='Supervivencia del más fuerte' WHERE entry=1223; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc6='Aparejos Lumak' WHERE entry=1224; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc6='Arboreto de Jandi' WHERE entry=1225; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc6='Peleteros de piel de kodo' WHERE entry=1227; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc6='Mina del Cañón Rojo' WHERE entry=1228; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc6='Peleteros de piel de kodo' WHERE entry=1229; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc6='Indumentarias Magar' WHERE entry=1230; /* icon_name: Magar\'s Cloth Goods */
UPDATE locales_points_of_interest SET icon_name_loc6='Casa de subastas: Entrañas' WHERE entry=1237; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc6='Archibald' WHERE entry=1239; /* icon_name: Archibald */
UPDATE locales_points_of_interest SET icon_name_loc6='Anya Maulray' WHERE entry=1240; /* icon_name: Anya Maulray */
UPDATE locales_points_of_interest SET icon_name_loc6='El Apothecarium' WHERE entry=1246; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc6='Campeona Cyssa Rosalba' WHERE entry=1263; /* icon_name: Champion Cyssa Dawnrose */
UPDATE locales_points_of_interest SET icon_name_loc6='Mesón La Horca' WHERE entry=1268; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc6='Morganus' WHERE entry=1270; /* icon_name: Morganus */
UPDATE locales_points_of_interest SET icon_name_loc6='Cain Pirosón' WHERE entry=1271; /* icon_name: Cain Firesong */
UPDATE locales_points_of_interest SET icon_name_loc6='Clérigo oscuro Beryl' WHERE entry=1272; /* icon_name: Dark Cleric Beryl */
UPDATE locales_points_of_interest SET icon_name_loc6='Marion Call' WHERE entry=1274; /* icon_name: Marion Call */
UPDATE locales_points_of_interest SET icon_name_loc6='Rupert Boch' WHERE entry=1275; /* icon_name: Rupert Boch */
UPDATE locales_points_of_interest SET icon_name_loc6='Austil de Mon' WHERE entry=1276; /* icon_name: Austil de Mon */
UPDATE locales_points_of_interest SET icon_name_loc6='Carolai Anise' WHERE entry=1277; /* icon_name: Carolai Anise */
UPDATE locales_points_of_interest SET icon_name_loc6='Vance Bajopenumbra' WHERE entry=1278; /* icon_name: Vance Undergloom */
UPDATE locales_points_of_interest SET icon_name_loc6='Enfermera Neela' WHERE entry=1279; /* icon_name: Nurse Neela */
UPDATE locales_points_of_interest SET icon_name_loc6='Clyde Kellen' WHERE entry=1280; /* icon_name: Clyde Kellen */
UPDATE locales_points_of_interest SET icon_name_loc6='Faruza' WHERE entry=1281; /* icon_name: Faruza */
UPDATE locales_points_of_interest SET icon_name_loc6='Shelene Rhobart' WHERE entry=1283; /* icon_name: Shelene Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc6='Rand Rhobart' WHERE entry=1284; /* icon_name: Rand Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc6='Bowen Brisboise' WHERE entry=1285; /* icon_name: Bowen Brisboise */
UPDATE locales_points_of_interest SET icon_name_loc6='Seikwa' WHERE entry=1287; /* icon_name: Seikwa */
UPDATE locales_points_of_interest SET icon_name_loc6='Gennia Tótem de Runa' WHERE entry=1288; /* icon_name: Gennia Runetotem */
UPDATE locales_points_of_interest SET icon_name_loc6='Yaw Crinafilada' WHERE entry=1289; /* icon_name: Yaw Sharpmane */
UPDATE locales_points_of_interest SET icon_name_loc6='Krang Pezuña Pétrea' WHERE entry=1292; /* icon_name: Krang Stonehoof */
UPDATE locales_points_of_interest SET icon_name_loc6='Narm Cazacielo' WHERE entry=1293; /* icon_name: Narm Skychaser */
UPDATE locales_points_of_interest SET icon_name_loc6='Pyall Trancosilencio' WHERE entry=1296; /* icon_name: Pyall Silentstride */
UPDATE locales_points_of_interest SET icon_name_loc6='Vira Pezuña Joven' WHERE entry=1297; /* icon_name: Vira Younghoof */
UPDATE locales_points_of_interest SET icon_name_loc6='Uthan Aguaserena' WHERE entry=1298; /* icon_name: Uthan Stillwater */
UPDATE locales_points_of_interest SET icon_name_loc6='Chaw Pellejofuerte' WHERE entry=1301; /* icon_name: Chaw Stronghide */
UPDATE locales_points_of_interest SET icon_name_loc6='Yonn Corte Profundo' WHERE entry=1302; /* icon_name: Yonn Deepcut */
UPDATE locales_points_of_interest SET icon_name_loc6='Banco de Cima del Trueno' WHERE entry=1303; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc6='Información al Ciudadano de Cima del Trueno' WHERE entry=1305; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc6='Ansekhwa' WHERE entry=1309; /* icon_name: Ansekhwa */
UPDATE locales_points_of_interest SET icon_name_loc6='Bulrug' WHERE entry=1310; /* icon_name: Bulrug */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Ancestros' WHERE entry=1314; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc6='Recinto de los Cazadores' WHERE entry=1315; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc6='Pozas de las Visiones' WHERE entry=1317; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc6='Pozas de las Visiones' WHERE entry=1318; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc6='Sala de los Espíritus' WHERE entry=1319; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc6='Recinto de los Cazadores' WHERE entry=1320; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc6='Herrería de Karn' WHERE entry=1323; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc6='La Alquimia de Bena' WHERE entry=1324; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc6='La Cocina de Aska' WHERE entry=1325; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc6='Encantadores Caminalba' WHERE entry=1326; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc6='Curación Espiritual' WHERE entry=1327; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc6='Anzuelos y Aparejos La Cumbre' WHERE entry=1328; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc6='Herboristería Holística' WHERE entry=1329; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc6='Armeros de Cima del Trueno' WHERE entry=1331; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc6='Geólogos Pezuña Pétrea' WHERE entry=1332; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc6='Mooranta' WHERE entry=1333; /* icon_name: Mooranta */
UPDATE locales_points_of_interest SET icon_name_loc6='Armeros de Cima del Trueno' WHERE entry=1334; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc6='Al\'ar' WHERE entry=1845; /* icon_name: Alchemist of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc6='Banco de Orgrimmar' WHERE entry=1901; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc6='Banco de Orgrimmar' WHERE entry=12627; /* icon_name: Bank of Orgrimmar */

SET NAMES 'latin1';
