-- File generated by Mangos Online Translation Editor (MOTE) v2.0
SET NAMES 'utf8';
UPDATE locales_achievement_reward SET subject_loc6='¡Por la Alianza!' WHERE entry=614;
UPDATE locales_achievement_reward SET subject_loc6='¡Por la Horda!' WHERE entry=619;
UPDATE locales_achievement_reward SET subject_loc6='¡Adelante, almirante!' WHERE entry=871;
UPDATE locales_achievement_reward SET subject_loc6='La Diplomática' WHERE entry=942;
UPDATE locales_achievement_reward SET subject_loc6='La Diplomática' WHERE entry=943;

SET NAMES 'latin1';
