-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc8='Bring me back to life' WHERE menu_id=0 AND id=4; /* option_text: Bring me back to life */
UPDATE locales_gossip_menu_option SET option_text_loc8='Bring me back to life' WHERE menu_id=0 AND id=5; /* option_text: Bring me back to life */
UPDATE locales_gossip_menu_option SET option_text_loc8='Show me my bank' WHERE menu_id=0 AND id=7; /* option_text: Show me my bank */
UPDATE locales_gossip_menu_option SET option_text_loc8='Auction!' WHERE menu_id=0 AND id=11; /* option_text: Auction! */
UPDATE locales_gossip_menu_option SET option_text_loc8='Can you tell me about this shard?' WHERE menu_id=21 AND id=1; /* option_text: Can you tell me about this shard? */
UPDATE locales_gossip_menu_option SET option_text_loc8='[PH] Get E.C.A.C.' WHERE menu_id=524 AND id=0; /* option_text: [PH] Get E.C.A.C. */
UPDATE locales_gossip_menu_option SET option_text_loc8='[PH] Get Thieves\' Tools' WHERE menu_id=524 AND id=1; /* option_text: [PH] Get Thieves\' Tools */
UPDATE locales_gossip_menu_option SET option_text_loc8='I need to know where the princess are, Kharan!' WHERE menu_id=1822 AND id=0; /* option_text: I need to know where the princess are, Kharan! */
UPDATE locales_gossip_menu_option SET option_text_loc8='I have paid your price, Gloom\'rel. Now teach me your secrets!' WHERE menu_id=1945 AND id=1; /* option_text: I have paid your price, Gloom\'rel. Now teach me your secrets! */
UPDATE locales_gossip_menu_option SET option_text_loc8='I want to examine this pylon.' WHERE menu_id=2177 AND id=0; /* option_text: I want to examine this pylon. */
UPDATE locales_gossip_menu_option SET option_text_loc8='I want to examine this pylon.' WHERE menu_id=2178 AND id=0; /* option_text: I want to examine this pylon. */
UPDATE locales_gossip_menu_option SET option_text_loc8='I want to examine this pylon.' WHERE menu_id=2179 AND id=0; /* option_text: I want to examine this pylon. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Transcript the Tablet' WHERE menu_id=2187 AND id=0; /* option_text: Transcript the Tablet */
UPDATE locales_gossip_menu_option SET option_text_loc8='I\'d like you to make me a new Cache of Mau\'ari please' WHERE menu_id=2703 AND id=2; /* option_text: I\'d like you to make me a new Cache of Mau\'ari please */
UPDATE locales_gossip_menu_option SET option_text_loc8='Hearthglen? But...' WHERE menu_id=2904 AND id=0; /* option_text: Hearthglen? But... */
UPDATE locales_gossip_menu_option SET option_text_loc8='You will have to excuse me, Lorax, I do not speak \'crazy\'.' WHERE menu_id=3049 AND id=0; /* option_text: You will have to excuse me, Lorax, I do not speak \'crazy\'. */
UPDATE locales_gossip_menu_option SET option_text_loc8='I lost Spectral Essence.' WHERE menu_id=3310 AND id=1; /* option_text: I lost Spectral Essence. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Do you know where I can find Half Pendant of Aquatic Agility?' WHERE menu_id=4041 AND id=1; /* option_text: Do you know where I can find Half Pendant of Aquatic Agility? */
UPDATE locales_gossip_menu_option SET option_text_loc8='Do you know where I can find Half Pendant of Aquatic Endurance?' WHERE menu_id=4042 AND id=1; /* option_text: Do you know where I can find Half Pendant of Aquatic Endurance? */
UPDATE locales_gossip_menu_option SET option_text_loc8='Ner\'zhul' WHERE menu_id=4764 AND id=2; /* option_text: Ner\'zhul */
UPDATE locales_gossip_menu_option SET option_text_loc8='Teach me how to create and apply a Runecloth Bandage, Doctor.' WHERE menu_id=5381 AND id=1; /* option_text: Teach me how to create and apply a Runecloth Bandage, Doctor. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Teach me how to create and apply a Heavy Runecloth Bandage, Doctor.' WHERE menu_id=5381 AND id=2; /* option_text: Teach me how to create and apply a Heavy Runecloth Bandage, Doctor. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Teach me how to create and apply a Runecloth Bandage, Doctor.' WHERE menu_id=5382 AND id=1; /* option_text: Teach me how to create and apply a Runecloth Bandage, Doctor. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Teach me how to create and apply a Heavy Runecloth Bandage, Doctor.' WHERE menu_id=5382 AND id=2; /* option_text: Teach me how to create and apply a Heavy Runecloth Bandage, Doctor. */
UPDATE locales_gossip_menu_option SET option_text_loc8='I know this is rather silly but a young ward who is a bit shy would like your hoofprint.' WHERE menu_id=5851 AND id=0; /* option_text: I know this is rather silly but a young ward who is a bit shy would like your hoofprint. */
UPDATE locales_gossip_menu_option SET option_text_loc8='This Dimensional Imploder sounds dangerous! How can I make one?' WHERE menu_id=6092 AND id=0; /* option_text: This Dimensional Imploder sounds dangerous! How can I make one? */
UPDATE locales_gossip_menu_option SET option_text_loc8='Learn recipe...' WHERE menu_id=6443 AND id=0; /* option_text: Learn recipe... */
UPDATE locales_gossip_menu_option SET option_text_loc8='May I have your report?' WHERE menu_id=6690 AND id=0; /* option_text: May I have your report? */
UPDATE locales_gossip_menu_option SET option_text_loc8='May I have your report?' WHERE menu_id=6691 AND id=0; /* option_text: May I have your report? */
UPDATE locales_gossip_menu_option SET option_text_loc8='May I have your report?' WHERE menu_id=6692 AND id=0; /* option_text: May I have your report? */
UPDATE locales_gossip_menu_option SET option_text_loc8='[ph]' WHERE menu_id=6799 AND id=0; /* option_text: [ph] */
UPDATE locales_gossip_menu_option SET option_text_loc8='You\'re free to go now. The way out is safe.' WHERE menu_id=7176 AND id=0; /* option_text: You\'re free to go now. The way out is safe. */
UPDATE locales_gossip_menu_option SET option_text_loc8='You\'re free to go now. The way out is safe.' WHERE menu_id=7186 AND id=0; /* option_text: You\'re free to go now. The way out is safe. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Take Blood Knight Insignia' WHERE menu_id=7486 AND id=0; /* option_text: Take Blood Knight Insignia */
UPDATE locales_gossip_menu_option SET option_text_loc8='I\'m on a bombing mission for Forward Commander Kingston. I need a gryphon destroyer!' WHERE menu_id=7970 AND id=1; /* option_text: I\'m on a bombing mission for Forward Commander Kingston. I need a gryphon destroyer! */
UPDATE locales_gossip_menu_option SET option_text_loc8='Send me to Raven\'s Wood!' WHERE menu_id=8304 AND id=4; /* option_text: Send me to Raven\'s Wood! */
UPDATE locales_gossip_menu_option SET option_text_loc8='[PH] Learn Ultrasafe Transporter.' WHERE menu_id=8306 AND id=0; /* option_text: [PH] Learn Ultrasafe Transporter. */
UPDATE locales_gossip_menu_option SET option_text_loc8='This Dimensional Imploder sounds dangerous! How can I make one?' WHERE menu_id=8308 AND id=0; /* option_text: This Dimensional Imploder sounds dangerous! How can I make one? */
UPDATE locales_gossip_menu_option SET option_text_loc8='Yes... yes, it\'s me.' WHERE menu_id=8616 AND id=0; /* option_text: Yes... yes, it\'s me. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Yes elder. Tell me more of the book.' WHERE menu_id=8617 AND id=0; /* option_text: Yes elder. Tell me more of the book. */
UPDATE locales_gossip_menu_option SET option_text_loc8='You gave the crew disguises?' WHERE menu_id=8775 AND id=0; /* option_text: You gave the crew disguises? */
UPDATE locales_gossip_menu_option SET option_text_loc8='I need to fly to the Windrunner. Official Business!' WHERE menu_id=8894 AND id=0; /* option_text: I need to fly to the Windrunner. Official Business! */
UPDATE locales_gossip_menu_option SET option_text_loc8='"Stash?' WHERE menu_id=9040 AND id=2; /* option_text: "Stash? */
UPDATE locales_gossip_menu_option SET option_text_loc8='"Stash?' WHERE menu_id=9041 AND id=2; /* option_text: "Stash? */
UPDATE locales_gossip_menu_option SET option_text_loc8='"Stash?' WHERE menu_id=9042 AND id=2; /* option_text: "Stash? */
UPDATE locales_gossip_menu_option SET option_text_loc8='Thank you for telling me your story.' WHERE menu_id=9182 AND id=0; /* option_text: Thank you for telling me your story. */
UPDATE locales_gossip_menu_option SET option_text_loc8='[PH] I want to deliver prisoner.' WHERE menu_id=9184 AND id=0; /* option_text: [PH] I want to deliver prisoner. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Take me to the Caverns of Time' WHERE menu_id=9205 AND id=0; /* option_text: Take me to the Caverns of Time */
UPDATE locales_gossip_menu_option SET option_text_loc8='lala' WHERE menu_id=9212 AND id=1; /* option_text: lala */
UPDATE locales_gossip_menu_option SET option_text_loc8='I would like to build a catapult.' WHERE menu_id=9904 AND id=0; /* option_text: I would like to build a catapult. */
UPDATE locales_gossip_menu_option SET option_text_loc8='I would like to build a demolisher.' WHERE menu_id=9904 AND id=1; /* option_text: I would like to build a demolisher. */
UPDATE locales_gossip_menu_option SET option_text_loc8='I would like to build a siege engine.' WHERE menu_id=9904 AND id=2; /* option_text: I would like to build a siege engine. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Hold on friend. Tell me what happened here.' WHERE menu_id=10036 AND id=0; /* option_text: Hold on friend. Tell me what happened here. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Lady Proudmoore. I am ready to go to Orgrimmar. Please open a portal.' WHERE menu_id=10189 AND id=0; /* option_text: Lady Proudmoore. I am ready to go to Orgrimmar. Please open a portal. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Thank you! I will be sure to notify you if I find anything else.' WHERE menu_id=10213 AND id=0; /* option_text: Thank you! I will be sure to notify you if I find anything else. */
UPDATE locales_gossip_menu_option SET option_text_loc8='If you want to know is male or female, look Frost Leopard by the tail.' WHERE menu_id=10273 AND id=0; /* option_text: If you want to know is male or female, look Frost Leopard by the tail. */
UPDATE locales_gossip_menu_option SET option_text_loc8='If you want to know is male or female, look Icepaw Bear by the tail.' WHERE menu_id=10274 AND id=0; /* option_text: If you want to know is male or female, look Icepaw Bear by the tail. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Watcher Analisis: Freya' WHERE menu_id=10368 AND id=2; /* option_text: Watcher Analisis: Freya */
UPDATE locales_gossip_menu_option SET option_text_loc8='Watcher Analisis: Hodir' WHERE menu_id=10368 AND id=3; /* option_text: Watcher Analisis: Hodir */
UPDATE locales_gossip_menu_option SET option_text_loc8='Watcher Analisis: Thorim' WHERE menu_id=10368 AND id=4; /* option_text: Watcher Analisis: Thorim */
UPDATE locales_gossip_menu_option SET option_text_loc8='Watcher Analisis: Mimiron' WHERE menu_id=10368 AND id=5; /* option_text: Watcher Analisis: Mimiron */
UPDATE locales_gossip_menu_option SET option_text_loc8='Arcanist Tubalin said you might be able to lend me a certain tabard.' WHERE menu_id=10854 AND id=0; /* option_text: Arcanist Tubalin said you might be able to lend me a certain tabard. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Would you renew my Silver Covenant disguise?' WHERE menu_id=10857 AND id=2; /* option_text: Would you renew my Silver Covenant disguise? */
UPDATE locales_gossip_menu_option SET option_text_loc8='I\'m ready to deliver the tome, Arcanist Tybalin.' WHERE menu_id=10858 AND id=1; /* option_text: I\'m ready to deliver the tome, Arcanist Tybalin. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Get me up into the skies, Sassy.' WHERE menu_id=11146 AND id=0; /* option_text: Get me up into the skies, Sassy. */
UPDATE locales_gossip_menu_option SET option_text_loc8='The word is given. The King-lich will accept death from our hands!' WHERE menu_id=11207 AND id=0; /* option_text: The word is given. The King-lich will accept death from our hands! */
UPDATE locales_gossip_menu_option SET option_text_loc8='Bossy, I need to ask something great of you.  I need to cut off your head to prove my loyalty to the Bloodsail Buccaneers, so they will allow me to infiltrate their ranks and hopefully discover their true intentions.
Booty Bay needs you, Bossy... now more than ever.' WHERE menu_id=11741 AND id=0; /* option_text: Bossy, I need to ask something great of you.  I need to cut off your head to prove my loyalty to the Bloodsail Buccaneers, so they will allow me to infiltrate their ranks and hopefully discover their true intentions.
Booty Bay needs you, Bossy... now more than ever. */
UPDATE locales_gossip_menu_option SET option_text_loc8='I was just wondering what you knew about the gnolls to the south. Someone has been giving them supplies to practice necromancy.' WHERE menu_id=11942 AND id=0; /* option_text: I was just wondering what you knew about the gnolls to the south. Someone has been giving them supplies to practice necromancy. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Is there something I can do at the Shrine of Malorne?' WHERE menu_id=12167 AND id=3; /* option_text: Is there something I can do at the Shrine of Malorne? */
UPDATE locales_gossip_menu_option SET option_text_loc8='Is there something I can do at the Shrine of Malorne?' WHERE menu_id=12168 AND id=3; /* option_text: Is there something I can do at the Shrine of Malorne? */
UPDATE locales_gossip_menu_option SET option_text_loc8='I am ready to meet with Anachronos, Ziradormi.' WHERE menu_id=12760 AND id=0; /* option_text: I am ready to meet with Anachronos, Ziradormi. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate.' WHERE menu_id=50007 AND id=0; /* option_text: Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate. */
UPDATE locales_gossip_menu_option SET option_text_loc8='Is there anything you would have of me?' WHERE menu_id=50012 AND id=0; /* option_text: Is there anything you would have of me? */

SET NAMES 'latin1';
