-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_creature SET name_loc8='Waypoint (Only GM can see it)',subname_loc8='Visual' WHERE entry=1; /* name: Waypoint (Only GM can see it) */ .* subname: Visual */
UPDATE locales_creature SET name_loc8='Innkeeper Sentinel Hill',subname_loc8='Innkeeper' WHERE entry=8999; /* name: Innkeeper Sentinel Hill */ .* subname: Innkeeper */
UPDATE locales_creature SET name_loc8='Wynne Larsone',subname_loc8='Robe Merchant' WHERE entry=11111; /* name: Wynne Larsone */ .* subname: Robe Merchant */
UPDATE locales_creature SET subname_loc8='The Head of The Black Flight' WHERE entry=11583; /* subname: The Head of The Black Flight */
UPDATE locales_creature SET subname_loc8='DO NOT DELETE' WHERE entry=12999; /* subname: DO NOT DELETE */
UPDATE locales_creature SET name_loc8='Barnu Cragcrush',subname_loc8='Stable Master' WHERE entry=19325; /* name: Barnu Cragcrush */ .* subname: Stable Master */
UPDATE locales_creature SET name_loc8='Hurlog Horde',subname_loc8='Warsong Gulch Battlemaster' WHERE entry=20002; /* name: Hurlog Horde */ .* subname: Warsong Gulch Battlemaster */
UPDATE locales_creature SET subname_loc8='PH MODEL: TASK 20039' WHERE entry=27681; /* subname: PH MODEL: TASK 20039 */
UPDATE locales_creature SET subname_loc8='Don Carlos\' Pet' WHERE entry=28168; /* subname: Don Carlos\' Pet */
UPDATE locales_creature SET name_loc8='Empowered Necromancer',subname_loc8='Cult of the Damned' WHERE entry=31774; /* name: Empowered Necromancer */ .* subname: Cult of the Damned */

SET NAMES 'latin1';
