-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc8='Darnassus Hippogryph Master' WHERE entry=91; /* icon_name: Darnassus Hippogryph Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Silver Enclave' WHERE entry=129; /* icon_name: Dalaran Silver Enclave */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Sunreaver\'s Sanctuary' WHERE entry=130; /* icon_name: Dalaran Sunreaver\'s Sanctuary */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Northern Bank' WHERE entry=131; /* icon_name: Dalaran Northern Bank */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Southern Bank' WHERE entry=132; /* icon_name: Dalaran Southern Bank */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Barber' WHERE entry=133; /* icon_name: Dalaran Barber */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Flight Master' WHERE entry=134; /* icon_name: Dalaran Flight Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Inn' WHERE entry=136; /* icon_name: Dalaran Inn */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Alliance Inn' WHERE entry=137; /* icon_name: Dalaran Alliance Inn */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Horde Inn' WHERE entry=138; /* icon_name: Dalaran Horde Inn */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Locksmith' WHERE entry=139; /* icon_name: Dalaran Locksmith */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Krasus\' Landing' WHERE entry=140; /* icon_name: Dalaran Krasus\' Landing */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Violet Citadel' WHERE entry=141; /* icon_name: Dalaran Violet Citadel */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Violet Hold' WHERE entry=142; /* icon_name: Dalaran Violet Hold */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Trade District' WHERE entry=143; /* icon_name: Dalaran Trade District */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Antonidas Memorial' WHERE entry=144; /* icon_name: Dalaran Antonidas Memorial */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Runeweaver Square' WHERE entry=145; /* icon_name: Dalaran Runeweaver Square */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Eventide' WHERE entry=146; /* icon_name: Dalaran Eventide */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Cemetary' WHERE entry=147; /* icon_name: Dalaran Cemetary */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Inscription Trainer' WHERE entry=148; /* icon_name: Dalaran Inscription Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Stable Master' WHERE entry=149; /* icon_name: Dalaran Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Mage Trainer' WHERE entry=150; /* icon_name: Dalaran Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Alchemy Trainer' WHERE entry=151; /* icon_name: Dalaran Alchemy Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Blacksmithing Trainer' WHERE entry=152; /* icon_name: Dalaran Blacksmithing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Enchanting Trainer' WHERE entry=153; /* icon_name: Dalaran Enchanting Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Engineering Trainer' WHERE entry=154; /* icon_name: Dalaran Engineering Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran First Aid Trainer' WHERE entry=155; /* icon_name: Dalaran First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Fishing Fountain' WHERE entry=156; /* icon_name: Dalaran Fishing Fountain */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Herbalism Trainer' WHERE entry=157; /* icon_name: Dalaran Herbalism Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Jewelcrafting Trainer' WHERE entry=158; /* icon_name: Dalaran Jewelcrafting Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Leatherworking Trainer' WHERE entry=159; /* icon_name: Dalaran Leatherworking Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Mining Trainer' WHERE entry=160; /* icon_name: Dalaran Mining Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Skinning Trainer' WHERE entry=161; /* icon_name: Dalaran Skinning Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Tailoring Trainer' WHERE entry=162; /* icon_name: Dalaran Tailoring Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Cloth Armor & Clothing' WHERE entry=163; /* icon_name: Dalaran Cloth Armor & Clothing */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Flowers' WHERE entry=164; /* icon_name: Dalaran Flowers */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Fruit Vendor' WHERE entry=165; /* icon_name: Dalaran Fruit Vendor */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran General & Trade Store' WHERE entry=166; /* icon_name: Dalaran General & Trade Store */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Pet Store' WHERE entry=167; /* icon_name: Dalaran Pet Store */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Pie, Pastry & Cake' WHERE entry=168; /* icon_name: Dalaran Pie, Pastry & Cake */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Reagents' WHERE entry=169; /* icon_name: Dalaran Reagents */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Toy Store' WHERE entry=170; /* icon_name: Dalaran Toy Store */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Trinkets' WHERE entry=171; /* icon_name: Dalaran Trinkets */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Melee Weapons' WHERE entry=172; /* icon_name: Dalaran Melee Weapons */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Ranged Weapons' WHERE entry=173; /* icon_name: Dalaran Ranged Weapons */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Staves & Wands' WHERE entry=174; /* icon_name: Dalaran Staves & Wands */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Wine & Cheese' WHERE entry=175; /* icon_name: Dalaran Wine & Cheese */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Auctioneer' WHERE entry=190; /* icon_name: Exodar, Auctioneer */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, bank' WHERE entry=191; /* icon_name: Exodar, bank */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Hippogryph Master' WHERE entry=192; /* icon_name: Exodar, Hippogryph Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Guild Master' WHERE entry=193; /* icon_name: Exodar, Guild Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Inn' WHERE entry=194; /* icon_name: Exodar, Inn */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Mailbox' WHERE entry=195; /* icon_name: Exodar, Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Stable Master' WHERE entry=196; /* icon_name: Exodar, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Weapon Master' WHERE entry=197; /* icon_name: Exodar, Weapon Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Druid Trainer' WHERE entry=198; /* icon_name: Exodar, Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Hunter Trainers' WHERE entry=199; /* icon_name: Exodar, Hunter Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Mage Trainers' WHERE entry=200; /* icon_name: Exodar, Mage Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Paladin Trainers' WHERE entry=201; /* icon_name: Exodar, Paladin Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Priest Trainers' WHERE entry=202; /* icon_name: Exodar, Priest Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Shaman Trainer' WHERE entry=203; /* icon_name: Exodar, Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Warrior Trainers' WHERE entry=204; /* icon_name: Exodar, Warrior Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Alchemist Trainers' WHERE entry=205; /* icon_name: Exodar, Alchemist Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Blacksmithing Trainers' WHERE entry=206; /* icon_name: Exodar, Blacksmithing Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Enchanters' WHERE entry=207; /* icon_name: Exodar, Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Engineering' WHERE entry=208; /* icon_name: Exodar, Engineering */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, First Aid Trainer' WHERE entry=209; /* icon_name: Exodar, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Fishing Trainer' WHERE entry=210; /* icon_name: Exodar, Fishing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Herbalist Trainer' WHERE entry=211; /* icon_name: Exodar, Herbalist Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar Inscription' WHERE entry=212; /* icon_name: Exodar Inscription */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Jewelcrafters' WHERE entry=213; /* icon_name: Exodar, Jewelcrafters */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Leatherworking' WHERE entry=214; /* icon_name: Exodar, Leatherworking */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Mining Trainers' WHERE entry=215; /* icon_name: Exodar, Mining Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Skinning Trainer' WHERE entry=216; /* icon_name: Exodar, Skinning Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Tailors' WHERE entry=217; /* icon_name: Exodar, Tailors */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Cook' WHERE entry=218; /* icon_name: Exodar, Cook */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Innkeeper' WHERE entry=219; /* icon_name: Azure Watch, Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Stable Master' WHERE entry=220; /* icon_name: Azure Watch, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Hunter Trainer' WHERE entry=221; /* icon_name: Azure Watch, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Mage Trainer' WHERE entry=222; /* icon_name: Azure Watch, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Paladin Trainer' WHERE entry=223; /* icon_name: Azure Watch, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Priest Trainer' WHERE entry=224; /* icon_name: Azure Watch, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Shaman Trainer' WHERE entry=225; /* icon_name: Azure Watch, Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Warrior Trainer' WHERE entry=226; /* icon_name: Azure Watch, Warrior Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Alchemist' WHERE entry=227; /* icon_name: Azure Watch, Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc8='Odesyus\' Landing, Blacksmith' WHERE entry=228; /* icon_name: Odesyus\' Landing, Blacksmith */
UPDATE locales_points_of_interest SET icon_name_loc8='Odesyus\' Landing, Cook' WHERE entry=229; /* icon_name: Odesyus\' Landing, Cook */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Engineering Trainer' WHERE entry=230; /* icon_name: Azure Watch, Engineering Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, First Aid Trainer' WHERE entry=231; /* icon_name: Azure Watch, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Ammen Ford, Fisherwoman' WHERE entry=232; /* icon_name: Ammen Ford, Fisherwoman */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Herbalist' WHERE entry=233; /* icon_name: Azure Watch, Herbalist */
UPDATE locales_points_of_interest SET icon_name_loc8='Stillpine Hold, Leatherworker' WHERE entry=234; /* icon_name: Stillpine Hold, Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc8='Azure Watch, Mining Trainer' WHERE entry=235; /* icon_name: Azure Watch, Mining Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Stillpine Hold, Skinner' WHERE entry=236; /* icon_name: Stillpine Hold, Skinner */
UPDATE locales_points_of_interest SET icon_name_loc8='Odesyus\' Landing, Tailor' WHERE entry=237; /* icon_name: Odesyus\' Landing, Tailor */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Leather & Mail Armor' WHERE entry=238; /* icon_name: Dalaran Leather & Mail Armor */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Plate Armor & Shields' WHERE entry=239; /* icon_name: Dalaran Plate Armor & Shields */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Cantina' WHERE entry=240; /* icon_name: Shattrath Cantina */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Bank Scryer' WHERE entry=241; /* icon_name: Shattrath Bank Scryer */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Inn Scryer' WHERE entry=242; /* icon_name: Shattrath Inn Scryer */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Taxi' WHERE entry=243; /* icon_name: Shattrath Taxi */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Stable Aldor' WHERE entry=244; /* icon_name: Shattrath Stable Aldor */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Stable Scryer' WHERE entry=245; /* icon_name: Shattrath Stable Scryer */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Battlemasters Alliance' WHERE entry=246; /* icon_name: Shattrath Battlemasters Alliance */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Battlemasters Horde' WHERE entry=247; /* icon_name: Shattrath Battlemasters Horde */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Alchemist' WHERE entry=248; /* icon_name: Shattrath Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Armor/Weapon Crafter' WHERE entry=249; /* icon_name: Shattrath Armor/Weapon Crafter */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Cook' WHERE entry=250; /* icon_name: Shattrath Cook */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Enchanters' WHERE entry=251; /* icon_name: Shattrath Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath First Aid' WHERE entry=252; /* icon_name: Shattrath First Aid */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Jewelcrafter' WHERE entry=253; /* icon_name: Shattrath Jewelcrafter */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Leatherworker' WHERE entry=254; /* icon_name: Shattrath Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Skinner' WHERE entry=255; /* icon_name: Shattrath Skinner */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Mana Loom' WHERE entry=256; /* icon_name: Shattrath Mana Loom */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Alchemy Lab' WHERE entry=257; /* icon_name: Shattrath Alchemy Lab */
UPDATE locales_points_of_interest SET icon_name_loc8='Scryer Gem Vendor' WHERE entry=258; /* icon_name: Scryer Gem Vendor */
UPDATE locales_points_of_interest SET icon_name_loc8='Aldor Gem Vendor' WHERE entry=259; /* icon_name: Aldor Gem Vendor */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Bank Aldor' WHERE entry=260; /* icon_name: Shattrath Bank Aldor */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Inn Aldor' WHERE entry=261; /* icon_name: Shattrath Inn Aldor */
UPDATE locales_points_of_interest SET icon_name_loc8='Shattrath Arena Battlemasters' WHERE entry=262; /* icon_name: Shattrath Arena Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc8='Exodar, Battlemasters' WHERE entry=263; /* icon_name: Exodar, Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc8='Arena Battlemaster Exodar' WHERE entry=264; /* icon_name: Arena Battlemaster Exodar */
UPDATE locales_points_of_interest SET icon_name_loc8='Darnassus Mage Trainer' WHERE entry=265; /* icon_name: Darnassus Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Darnassus Paladin Trainer' WHERE entry=266; /* icon_name: Darnassus Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Sewer Arena' WHERE entry=270; /* icon_name: Dalaran Sewer Arena */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Sewer Bank' WHERE entry=271; /* icon_name: Dalaran Sewer Bank */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Sewer Inn' WHERE entry=272; /* icon_name: Dalaran Sewer Inn */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Sewer Tunnel' WHERE entry=273; /* icon_name: Dalaran Sewer Tunnel */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Sewer Vendors' WHERE entry=274; /* icon_name: Dalaran Sewer Vendors */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Auction House' WHERE entry=349; /* icon_name: Silvermoon City, Auction House */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Auction House' WHERE entry=350; /* icon_name: Silvermoon City, Auction House */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Bank' WHERE entry=351; /* icon_name: Silvermoon City, Bank */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Bank' WHERE entry=352; /* icon_name: Silvermoon City, Bank */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Flight Master' WHERE entry=353; /* icon_name: Silvermoon City, Flight Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Guild House' WHERE entry=354; /* icon_name: Silvermoon City, Guild House */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Inn' WHERE entry=355; /* icon_name: Silvermoon City, Inn */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Inn' WHERE entry=356; /* icon_name: Silvermoon City, Inn */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Mailbox' WHERE entry=357; /* icon_name: Silvermoon City, Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Stable Master' WHERE entry=358; /* icon_name: Silvermoon City, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Weapon Master' WHERE entry=359; /* icon_name: Silvermoon City, Weapon Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Battlemasters' WHERE entry=360; /* icon_name: Silvermoon City, Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Druid Trainer' WHERE entry=361; /* icon_name: Silvermoon City, Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Hunter Trainer' WHERE entry=362; /* icon_name: Silvermoon City, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Mage Trainer' WHERE entry=363; /* icon_name: Silvermoon City, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Paladin Trainer' WHERE entry=364; /* icon_name: Silvermoon City, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Priest Trainer' WHERE entry=365; /* icon_name: Silvermoon City, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Rogue Trainer' WHERE entry=366; /* icon_name: Silvermoon City, Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Warlock Trainers' WHERE entry=367; /* icon_name: Silvermoon City, Warlock Trainers */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Alchemy' WHERE entry=368; /* icon_name: Silvermoon City, Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Blacksmithing' WHERE entry=369; /* icon_name: Silvermoon City, Blacksmithing */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Cooking' WHERE entry=370; /* icon_name: Silvermoon City, Cooking */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Enchanting' WHERE entry=371; /* icon_name: Silvermoon City, Enchanting */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Engineering' WHERE entry=372; /* icon_name: Silvermoon City, Engineering */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, First Aid' WHERE entry=373; /* icon_name: Silvermoon City, First Aid */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Fishing' WHERE entry=374; /* icon_name: Silvermoon City, Fishing */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Herbalism' WHERE entry=375; /* icon_name: Silvermoon City, Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City Inscription' WHERE entry=376; /* icon_name: Silvermoon City Inscription */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Jewelcrafting' WHERE entry=377; /* icon_name: Silvermoon City, Jewelcrafting */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Leatherworking' WHERE entry=378; /* icon_name: Silvermoon City, Leatherworking */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Mining' WHERE entry=379; /* icon_name: Silvermoon City, Mining */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Skinning' WHERE entry=380; /* icon_name: Silvermoon City, Skinning */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Tailoring' WHERE entry=381; /* icon_name: Silvermoon City, Tailoring */
UPDATE locales_points_of_interest SET icon_name_loc8='Silvermoon City, Mana Loom' WHERE entry=382; /* icon_name: Silvermoon City, Mana Loom */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Innkeeper' WHERE entry=383; /* icon_name: Falconwing Square, Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Stable Master' WHERE entry=384; /* icon_name: Falconwing Square, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Hunter Trainer' WHERE entry=385; /* icon_name: Falconwing Square, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Mage Trainer' WHERE entry=386; /* icon_name: Falconwing Square, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Priest Trainer' WHERE entry=388; /* icon_name: Falconwing Square, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Rogue Trainer' WHERE entry=389; /* icon_name: Falconwing Square, Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Warlock Trainer' WHERE entry=390; /* icon_name: Falconwing Square, Warlock Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Saltheril\'s Haven, Alchemist' WHERE entry=391; /* icon_name: Saltheril\'s Haven, Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc8='Farstrider Retreat, Blacksmith' WHERE entry=392; /* icon_name: Farstrider Retreat, Blacksmith */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Cook' WHERE entry=393; /* icon_name: Falconwing Square, Cook */
UPDATE locales_points_of_interest SET icon_name_loc8='Saltheril\'s Haven, Enchanter' WHERE entry=394; /* icon_name: Saltheril\'s Haven, Enchanter */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, First Aid Trainer' WHERE entry=395; /* icon_name: Falconwing Square, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Saltheril\'s Haven, Herbalist' WHERE entry=396; /* icon_name: Saltheril\'s Haven, Herbalist */
UPDATE locales_points_of_interest SET icon_name_loc8='Falconwing Square, Jewelcrafter' WHERE entry=397; /* icon_name: Falconwing Square, Jewelcrafter */
UPDATE locales_points_of_interest SET icon_name_loc8='Eversong Woods, Leatherworker' WHERE entry=398; /* icon_name: Eversong Woods, Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc8='Eversong Woods, Skinner' WHERE entry=399; /* icon_name: Eversong Woods, Skinner */
UPDATE locales_points_of_interest SET icon_name_loc8='Saltheril\'s Haven, Tailor' WHERE entry=400; /* icon_name: Saltheril\'s Haven, Tailor */
UPDATE locales_points_of_interest SET icon_name_loc8='Dalaran Archaeology Trainer' WHERE entry=454; /* icon_name: Dalaran Archaeology Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Ironforge Druid Trainer' WHERE entry=455; /* icon_name: Ironforge Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Ironforge Archaeology' WHERE entry=456; /* icon_name: Ironforge Archaeology */
UPDATE locales_points_of_interest SET icon_name_loc8='Stormwind Druid Trainer' WHERE entry=457; /* icon_name: Stormwind Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc8='Orgrimmar Ethereals' WHERE entry=458; /* icon_name: Orgrimmar Ethereals */
UPDATE locales_points_of_interest SET icon_name_loc8='Orgrimmar Battlemasters' WHERE entry=459; /* icon_name: Orgrimmar Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc8='Darkmoon Game Tokens' WHERE entry=460; /* icon_name: Darkmoon Game Tokens */
UPDATE locales_points_of_interest SET icon_name_loc8='Darnassus Blacksmithing' WHERE entry=462; /* icon_name: Darnassus Blacksmithing */
UPDATE locales_points_of_interest SET icon_name_loc8='AAA Tonk Arena' WHERE entry=463; /* icon_name: AAA Tonk Arena */
UPDATE locales_points_of_interest SET icon_name_loc8='AAA Cannon' WHERE entry=464; /* icon_name: AAA Cannon */
UPDATE locales_points_of_interest SET icon_name_loc8='AAA Whack-a-Gnoll' WHERE entry=465; /* icon_name: AAA Whack-a-Gnoll */
UPDATE locales_points_of_interest SET icon_name_loc8='AAA Ring Toss' WHERE entry=466; /* icon_name: AAA Ring Toss */
UPDATE locales_points_of_interest SET icon_name_loc8='AAA Shooting Gallery' WHERE entry=467; /* icon_name: AAA Shooting Gallery */
UPDATE locales_points_of_interest SET icon_name_loc8='AAA Fortune Teller' WHERE entry=468; /* icon_name: AAA Fortune Teller */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Banker' WHERE entry=469; /* icon_name: Theramore Banker */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Hunter' WHERE entry=470; /* icon_name: Theramore Hunter */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Paladin' WHERE entry=472; /* icon_name: Theramore Paladin */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Priest' WHERE entry=473; /* icon_name: Theramore Priest */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Rogue' WHERE entry=474; /* icon_name: Theramore Rogue */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Shaman' WHERE entry=475; /* icon_name: Theramore Shaman */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Warlock' WHERE entry=476; /* icon_name: Theramore Warlock */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Warrior' WHERE entry=477; /* icon_name: Theramore Warrior */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Alchemy' WHERE entry=478; /* icon_name: Theramore Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Archaeology' WHERE entry=479; /* icon_name: Theramore Archaeology */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Blacksmithing' WHERE entry=480; /* icon_name: Theramore Blacksmithing */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Cooking' WHERE entry=481; /* icon_name: Theramore Cooking */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Enchanting' WHERE entry=482; /* icon_name: Theramore Enchanting */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Engineering' WHERE entry=483; /* icon_name: Theramore Engineering */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore First Aid' WHERE entry=484; /* icon_name: Theramore First Aid */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Fishing' WHERE entry=485; /* icon_name: Theramore Fishing */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Herbalism' WHERE entry=486; /* icon_name: Theramore Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Inscription' WHERE entry=487; /* icon_name: Theramore Inscription */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Jewelcrafting' WHERE entry=488; /* icon_name: Theramore Jewelcrafting */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Leatherworking' WHERE entry=489; /* icon_name: Theramore Leatherworking */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Mining' WHERE entry=490; /* icon_name: Theramore Mining */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Riding' WHERE entry=491; /* icon_name: Theramore Riding */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Skinning' WHERE entry=492; /* icon_name: Theramore Skinning */
UPDATE locales_points_of_interest SET icon_name_loc8='Theramore Tailoring' WHERE entry=493; /* icon_name: Theramore Tailoring */
UPDATE locales_points_of_interest SET icon_name_loc8='Flight Master of Orgrimmar' WHERE entry=1902; /* icon_name: Flight Master of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc8='Embassy of the Horde' WHERE entry=1903; /* icon_name: Embassy of the Horde */
UPDATE locales_points_of_interest SET icon_name_loc8='Orgrimmar: ' WHERE entry=1912; /* icon_name: Orgrimmar: */
UPDATE locales_points_of_interest SET icon_name_loc8='Orgrimmar: The auction house' WHERE entry=2403; /* icon_name: Orgrimmar: The auction house */
UPDATE locales_points_of_interest SET icon_name_loc8='Stable Master of Orgrimmar' WHERE entry=4902; /* icon_name: Stable Master of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc8='Orgrimmar: Portals' WHERE entry=12245; /* icon_name: Orgrimmar: Portals */
UPDATE locales_points_of_interest SET icon_name_loc8='Orgrimmar: The auction house' WHERE entry=12628; /* icon_name: Orgrimmar: The auction house */

SET NAMES 'latin1';
