-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=401 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=401 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=401 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=401 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=401 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=401 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=401 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=401 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=401 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=421 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=421 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=421 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=421 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=421 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=421 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=421 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=421 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=421 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=421 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=421 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=421 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=421 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=435 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=435 AND id=5; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=435 AND id=6; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=435 AND id=7; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=435 AND id=8; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=435 AND id=11; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=435 AND id=12; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=435 AND id=13; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=721 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=740 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=740 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=740 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=740 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=740 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=740 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=751 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=751 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=751 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=751 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=751 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=751 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=751 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=751 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=751 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=751 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=751 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=751 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=1942 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=1942 AND id=2; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=1942 AND id=3; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=1942 AND id=4; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=1942 AND id=5; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=1942 AND id=6; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=1942 AND id=7; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=1942 AND id=9; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=1942 AND id=10; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=1942 AND id=11; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=1942 AND id=12; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=1942 AND id=13; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=1942 AND id=15; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=1942 AND id=16; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=1949 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=1949 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=1949 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=1949 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=1949 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=1949 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=1949 AND id=6; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=1949 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=1949 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=1951 AND id=5; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=2121 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=2121 AND id=3; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=2121 AND id=4; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=2121 AND id=6; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=2121 AND id=7; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=2121 AND id=9; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=2121 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=2144 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=2144 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=2144 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=2144 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=2144 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=2144 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=2144 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=2144 AND id=7; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=2168 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=2168 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=2168 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=2168 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=2168 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=2168 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=2168 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=2168 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=2168 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=2168 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=2168 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=2168 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=2168 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=2343 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=2343 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=2343 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=2343 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=2343 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=2351 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=2351 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=2351 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=2351 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=2351 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=2351 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=2351 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=2351 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=2351 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=2351 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=2352 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=2352 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=2352 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=2352 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=2352 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=2352 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=2352 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=2847 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=2847 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=2847 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=2847 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=2847 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=2847 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=2847 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=2847 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=2847 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=2847 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=2847 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=2847 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=2847 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=2848 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=2848 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=2848 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=2848 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=2848 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=2848 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=2849 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=2849 AND id=14; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=3127 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=3127 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=3127 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3283 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3283 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3283 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3283 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=3283 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3283 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3283 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3284 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3284 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3284 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3284 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3284 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3284 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3284 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3284 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3284 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3284 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3284 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3284 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3284 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=3329 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3329 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=3329 AND id=2; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3329 AND id=3; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3330 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3330 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3330 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3330 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3330 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3330 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3330 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3330 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3330 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3330 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3330 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3330 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3354 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=3354 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3354 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3354 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3354 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3354 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3355 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3355 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3355 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3355 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3355 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3355 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3355 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3355 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3355 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3355 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3355 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3355 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3355 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=3506 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=3506 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=3506 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=3506 AND id=3; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=3506 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=3519 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3519 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3519 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=3519 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3519 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3519 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=3519 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3519 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3519 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3532 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3532 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3532 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3532 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3532 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3532 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3532 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3532 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3532 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3532 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3532 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3532 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3532 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=3533 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=3533 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=3533 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=3533 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3545 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3545 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=3545 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3545 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3545 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3545 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3545 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3558 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3558 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3558 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3558 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3558 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3558 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3558 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3558 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3558 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3558 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3558 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3558 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3558 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=3564 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3564 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3564 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3564 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3564 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3572 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3572 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3572 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3572 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3572 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3572 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3572 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3572 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3572 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3572 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=3580 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='굴단' WHERE menu_id=4764 AND id=0; /* option_text: Gul\'dan */
UPDATE locales_gossip_menu_option SET option_text_loc1='켈투자드' WHERE menu_id=4764 AND id=1; /* option_text: Kel\'Thuzad */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5222 AND id=2; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=5222 AND id=4; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5262 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5268 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=5268 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5270 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5272 AND id=3; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=5274 AND id=4; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5276 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=5276 AND id=6; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='무기 전문가' WHERE menu_id=7633 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=7649 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=7649 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=7649 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=7649 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=7649 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=7649 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=7649 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=7667 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=7667 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=7667 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=7667 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=7667 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=7667 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=7667 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=7667 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=7667 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=7667 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=7667 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=7667 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=7667 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=7667 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=7777 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='무기 전문가' WHERE menu_id=7777 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='투기장 사무관' WHERE menu_id=7786 AND id=0; /* option_text: Arena Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=7787 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=7787 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=7787 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=7787 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=7787 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=7787 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=7787 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=7788 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=7788 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=7788 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=7788 AND id=3; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=7788 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=7788 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=7788 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=7788 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=7788 AND id=8; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=7788 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=7788 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=7788 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=7788 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=7788 AND id=13; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='실버문 여관' WHERE menu_id=7845 AND id=0; /* option_text: Silvermoon City Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=8129 AND id=1; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=8137 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=8137 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=8137 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=8137 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=8137 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=8137 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=8137 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8138 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8138 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8138 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8138 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=8138 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8138 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=8138 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=8138 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=8138 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8138 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8138 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=8138 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8138 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=8138 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=8196 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=8196 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=8196 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=8196 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=8196 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=8196 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=8196 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8205 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8205 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8205 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8205 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=8205 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8205 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=8205 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=8205 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=8205 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8205 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8205 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=8205 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8205 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=8205 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=8282 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=8282 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 조련사' WHERE menu_id=8282 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=8282 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8282 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=8282 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 실험대' WHERE menu_id=8282 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8326 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8326 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8326 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8326 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8326 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8326 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8326 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8326 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=8357 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=8357 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 조련사' WHERE menu_id=8357 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=8357 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8357 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=8357 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 실험대' WHERE menu_id=8357 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8403 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8403 AND id=2; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8403 AND id=3; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8403 AND id=4; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8403 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8403 AND id=6; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8403 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8403 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=8419 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=8419 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 조련사' WHERE menu_id=8419 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=8419 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8419 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=8419 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 실험대' WHERE menu_id=8419 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8424 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8424 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8424 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8424 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8424 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8424 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8424 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8424 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=8590 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=8611 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=8611 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8994 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8994 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8995 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8996 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8996 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8997 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8997 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8999 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8999 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9000 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9001 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9001 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9002 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9002 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9017 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9017 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9018 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9018 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9025 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9025 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9026 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9026 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9038 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9038 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9040 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9041 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9042 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9042 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9043 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9043 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9073 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='처녀의 몽상호' WHERE menu_id=9074 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9074 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='처녀의 몽상호' WHERE menu_id=9075 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc1='처녀의 몽상호' WHERE menu_id=9076 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9076 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='X-51 황천로켓' WHERE menu_id=9191 AND id=0; /* option_text: X-51 Nether-Rocket */
UPDATE locales_gossip_menu_option SET option_text_loc1='시험용 고블린 날씨 변환기 01-B' WHERE menu_id=9191 AND id=2; /* option_text: Goblin Weather Machine - Prototype 01-B */
UPDATE locales_gossip_menu_option SET option_text_loc1='새끼 히포그리프' WHERE menu_id=9192 AND id=1; /* option_text: Hippogryph Hatchling */
UPDATE locales_gossip_menu_option SET option_text_loc1='길들인 거북이' WHERE menu_id=9192 AND id=2; /* option_text: Riding Turtle */
UPDATE locales_gossip_menu_option SET option_text_loc1='영원한 보라색 폭죽' WHERE menu_id=9193 AND id=1; /* option_text: Perpetual Purple Firework */
UPDATE locales_gossip_menu_option SET option_text_loc1='오우거 우상 조각' WHERE menu_id=9193 AND id=2; /* option_text: Carved Ogre Idol */
UPDATE locales_gossip_menu_option SET option_text_loc1='신비의 휘장' WHERE menu_id=9193 AND id=3; /* option_text: Tabard of the Arcane */
UPDATE locales_gossip_menu_option SET option_text_loc1='광휘의 휘장' WHERE menu_id=9193 AND id=4; /* option_text: Tabard of Brilliance */
UPDATE locales_gossip_menu_option SET option_text_loc1='수호의 휘장' WHERE menu_id=9193 AND id=5; /* option_text: Tabard of the Defender */
UPDATE locales_gossip_menu_option SET option_text_loc1='분노의 휘장' WHERE menu_id=9193 AND id=6; /* option_text: Tabard of Fury */
UPDATE locales_gossip_menu_option SET option_text_loc1='자연의 휘장' WHERE menu_id=9193 AND id=7; /* option_text: Tabard of Nature */
UPDATE locales_gossip_menu_option SET option_text_loc1='공허의 휘장' WHERE menu_id=9193 AND id=8; /* option_text: Tabard of the Void */
UPDATE locales_gossip_menu_option SET option_text_loc1='랜드로의 애완동물 상자' WHERE menu_id=9193 AND id=9; /* option_text: Landro\'s Pet Box */
UPDATE locales_gossip_menu_option SET option_text_loc1='소풍 바구니' WHERE menu_id=9194 AND id=0; /* option_text: Picnic Basket */
UPDATE locales_gossip_menu_option SET option_text_loc1='구슬 속의 임프' WHERE menu_id=9194 AND id=2; /* option_text: Imp in a Ball */
UPDATE locales_gossip_menu_option SET option_text_loc1='고블린 검보 스튜 솥' WHERE menu_id=9195 AND id=0; /* option_text: Goblin Gumbo Kettle */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 의자' WHERE menu_id=9195 AND id=1; /* option_text: Fishing Chair */
UPDATE locales_gossip_menu_option SET option_text_loc1='유령 호랑이 고삐' WHERE menu_id=9195 AND id=2; /* option_text: Reins of the Spectral Tiger */
UPDATE locales_gossip_menu_option SET option_text_loc1='종이 비행기 조립도구' WHERE menu_id=9196 AND id=0; /* option_text: Paper Flying Machine Kit */
UPDATE locales_gossip_menu_option SET option_text_loc1='로켓닭' WHERE menu_id=9196 AND id=1; /* option_text: Rocket Chicken */
UPDATE locales_gossip_menu_option SET option_text_loc1='용 연' WHERE menu_id=9196 AND id=2; /* option_text: Dragon Kite */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9558 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9559 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='일리단의 발걸음' WHERE menu_id=9629 AND id=0; /* option_text: Path of Illidan */
UPDATE locales_gossip_menu_option SET option_text_loc1='에테리얼 영혼의 무역상' WHERE menu_id=9629 AND id=2; /* option_text: Ethereal Soul-Trader */
UPDATE locales_gossip_menu_option SET option_text_loc1='파티 수류탄' WHERE menu_id=9682 AND id=0; /* option_text: Party G.R.E.N.A.D.E. */
UPDATE locales_gossip_menu_option SET option_text_loc1='점유의 깃발' WHERE menu_id=9682 AND id=1; /* option_text: The Flag of Ownership */
UPDATE locales_gossip_menu_option SET option_text_loc1='투기장' WHERE menu_id=10043 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=10043 AND id=3; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=10043 AND id=9; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc1='상업 지구' WHERE menu_id=10056 AND id=5; /* option_text: Trade District */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=10056 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=10078 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=10078 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=10078 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=10078 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=10078 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=10078 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=10078 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=10078 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=10078 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=10078 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=10078 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=10078 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=10078 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=10078 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='상급 마법사' WHERE menu_id=10082 AND id=3; /* option_text: Mage Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc1='투기장' WHERE menu_id=10106 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=10106 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=10106 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽 방어구 상점' WHERE menu_id=10170 AND id=1; /* option_text: Leather Armor */
UPDATE locales_gossip_menu_option SET option_text_loc1='사슬 방어구 상점' WHERE menu_id=10170 AND id=2; /* option_text: Mail Armor */
UPDATE locales_gossip_menu_option SET option_text_loc1='방패 상점' WHERE menu_id=10170 AND id=4; /* option_text: Shields */
UPDATE locales_gossip_menu_option SET option_text_loc1='전문 보석세공인' WHERE menu_id=10173 AND id=6; /* option_text: Jewelcrafting Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법 재료 상인' WHERE menu_id=10173 AND id=9; /* option_text: Reagents */
UPDATE locales_gossip_menu_option SET option_text_loc1='무기 상점' WHERE menu_id=10173 AND id=13; /* option_text: Weapons */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=10265 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=10265 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=10265 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=10265 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=10265 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=10265 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=10265 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='흔들 호랑이' WHERE menu_id=10330 AND id=0; /* option_text: Sandbox Tiger */
UPDATE locales_gossip_menu_option SET option_text_loc1='영웅급 보라색 셔츠' WHERE menu_id=10330 AND id=1; /* option_text: Epic Purple Shirt */
UPDATE locales_gossip_menu_option SET option_text_loc1='장난감 칼 선반' WHERE menu_id=10330 AND id=2; /* option_text: Foam Sword Rack */
UPDATE locales_gossip_menu_option SET option_text_loc1='세나리우스의 길' WHERE menu_id=10533 AND id=0; /* option_text: Path of Cenarius */
UPDATE locales_gossip_menu_option SET option_text_loc1='오우거 종이박' WHERE menu_id=10533 AND id=1; /* option_text: Ogre Pinata */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법 수탉' WHERE menu_id=10533 AND id=2; /* option_text: Magic Rooster */
UPDATE locales_gossip_menu_option SET option_text_loc1='북풍의 땅' WHERE menu_id=10668 AND id=0; /* option_text: Borean Tundra */
UPDATE locales_gossip_menu_option SET option_text_loc1='울부짖는 협만' WHERE menu_id=10668 AND id=1; /* option_text: Howling Fjord */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=10767 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=10767 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=10767 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=10767 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=10767 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=10767 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=10767 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=10767 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=10767 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=10767 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=10767 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=10767 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=10767 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=10768 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=10768 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=10768 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=10768 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=10768 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=10768 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=10769 AND id=2; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=10769 AND id=7; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc1='투스카르 연' WHERE menu_id=10810 AND id=1; /* option_text: Tuskarr Kite */
UPDATE locales_gossip_menu_option SET option_text_loc1='새끼 유령 호랑이' WHERE menu_id=10810 AND id=2; /* option_text: Spectral Tiger Cub */
UPDATE locales_gossip_menu_option SET option_text_loc1='용사의 전당' WHERE menu_id=11845 AND id=0; /* option_text: Champions\' Hall */
UPDATE locales_gossip_menu_option SET option_text_loc1='스톰윈드 공원' WHERE menu_id=11845 AND id=2; /* option_text: The Park */
UPDATE locales_gossip_menu_option SET option_text_loc1='스톰윈드 왕궁' WHERE menu_id=11845 AND id=5; /* option_text: Stormwind Keep */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=11848 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='마구간지기' WHERE menu_id=11848 AND id=4; /* option_text: Horse Breeder */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=11969 AND id=5; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=11976 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=11976 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=11976 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=11976 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=11976 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=11976 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=11976 AND id=7; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=11977 AND id=0; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=11977 AND id=1; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=11977 AND id=2; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=11977 AND id=3; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='일용품 상인' WHERE menu_id=11978 AND id=0; /* option_text: General Goods */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법 재료 및 독극물 상인' WHERE menu_id=11978 AND id=1; /* option_text: Poisons & Reagents */
UPDATE locales_gossip_menu_option SET option_text_loc1='직업용품 상인' WHERE menu_id=11978 AND id=3; /* option_text: Trade Supplies */
UPDATE locales_gossip_menu_option SET option_text_loc1='힘의 골짜기' WHERE menu_id=12637 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc1='명예의 골짜기' WHERE menu_id=12637 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc1='힘의 골짜기' WHERE menu_id=12638 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc1='명예의 골짜기' WHERE menu_id=12638 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc1='힘의 골짜기' WHERE menu_id=12639 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc1='명예의 골짜기' WHERE menu_id=12639 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc1='아마니 용매' WHERE menu_id=12785 AND id=2; /* option_text: Amani Dragonhawk */

SET NAMES 'latin1';
