-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc1='살아있습니다!' WHERE entry=2000000711; /* content: It\'s alive! */

SET NAMES 'latin1';
