-- File generated by Mangos Online Translation Editor (MOTE) v2.00
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc9='I would like to inform the secret code to get a pet, murloc.',box_text_loc9='2222' WHERE menu_id=7034 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='Here\'s a gold, buy yourself something nice.',box_text_loc9='Do you really want to bribe Olga?' WHERE menu_id=9014 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='Purchase a Dual Talent Specialization.',box_text_loc9='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE menu_id=10371 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='I no longer wish to gain experience.',box_text_loc9='Are you certain you wish to stop gaining experience?' WHERE menu_id=10638 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='May bee a couple copper will loosen your toungue. Now tell me, did you se who killed the Furlbrows?',box_text_loc9='Are you sure you want to give this hobo money?' WHERE menu_id=11635 AND id=1;
UPDATE locales_gossip_menu_option SET option_text_loc9='Whatever, Duncan.  Grab a mop and get to work.',box_text_loc9='Will you pay "Pretty Boy" Duncan 1 gold to swab the decks for you?' WHERE menu_id=12723 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='Journey to the fair will cost you',box_text_loc9='Journey to the fair will cost you' WHERE menu_id=12992 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='Journey to the fair will cost you',box_text_loc9='Journey to the fair will cost you' WHERE menu_id=13124 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='You may begin your ritual, we will defend you.',box_text_loc9='Do you want to start the encounter?' WHERE menu_id=13322 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='Teleport me to the cannon.',box_text_loc9='Teleportation to the cannon will cost:' WHERE menu_id=13352 AND id=0;

SET NAMES 'latin1';
