-- File generated by Mangos Online Translation Editor (MOTE) v2.0
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc6='I wish to unlearn Dragonscale Leatherworking.',box_text_loc6='Do you really want to unlearn your leatherworking specialty and lose all associated recipes?' WHERE menu_id=3067 AND id=2;
UPDATE locales_gossip_menu_option SET box_text_loc6='Do you really want to unlearn your leatherworking specialty and lose all associated recipes?' WHERE menu_id=3067 AND id=2;
UPDATE locales_gossip_menu_option SET option_text_loc6='I wish to unlearn Elemental Leatherworking.',box_text_loc6='Do you really want to unlearn your leatherworking specialty and lose all associated recipes?' WHERE menu_id=3070 AND id=2;
UPDATE locales_gossip_menu_option SET box_text_loc6='Do you really want to unlearn your leatherworking specialty and lose all associated recipes?' WHERE menu_id=3070 AND id=2;
UPDATE locales_gossip_menu_option SET option_text_loc6='I wish to unlearn Tribal Leatherworking.',box_text_loc6='Do you really want to unlearn your leatherworking specialty and lose all associated recipes?' WHERE menu_id=3072 AND id=2;
UPDATE locales_gossip_menu_option SET box_text_loc6='Do you really want to unlearn your leatherworking specialty and lose all associated recipes?' WHERE menu_id=3072 AND id=2;
UPDATE locales_gossip_menu_option SET box_text_loc6='2222' WHERE menu_id=7034 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc6='I wish to unlearn Gnomish engineer.',box_text_loc6='Do you really want to unlearn your engineer specialty and lose all associated recipes?' WHERE menu_id=7058 AND id=2;
UPDATE locales_gossip_menu_option SET option_text_loc6='I wish to unlearn Goblin engineer.',box_text_loc6='Do you really want to unlearn your engineer specialty and lose all associated recipes?' WHERE menu_id=7058 AND id=3;
UPDATE locales_gossip_menu_option SET option_text_loc6='Purchase a Dual Talent Specialization.',box_text_loc6='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE menu_id=10371 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc6='Ask about the orphan.',box_text_loc6='You may choose to care for an Oracle orphan or a frenzyheart orphan. But you will not be able help both.' WHERE menu_id=10502 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc6='May bee a couple copper will loosen your toungue. Now tell me, did you se who killed the Furlbrows?',box_text_loc6='Are you sure you want to give this hobo money?' WHERE menu_id=11635 AND id=1;
UPDATE locales_gossip_menu_option SET box_text_loc6='Are you sure you want to give this hobo money?' WHERE menu_id=11635 AND id=1;
UPDATE locales_gossip_menu_option SET option_text_loc6='Journey to the fair will cost you',box_text_loc6='Journey to the fair will cost you' WHERE menu_id=12992 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc6='Journey to the fair will cost you',box_text_loc6='Journey to the fair will cost you' WHERE menu_id=13124 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc6='<Pay 10 000 gold.>',box_text_loc6='Do you want to pay?' WHERE menu_id=57800 AND id=0;

SET NAMES 'latin1';
