-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=401 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=401 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=401 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=401 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=401 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=401 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=401 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=401 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=401 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=421 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=421 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=421 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=421 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=421 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=421 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=421 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=421 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=421 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=421 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=421 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=421 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=421 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Hôtel des ventes' WHERE menu_id=435 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des griffons' WHERE menu_id=435 AND id=5; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des guildes' WHERE menu_id=435 AND id=6; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Serrurier' WHERE menu_id=435 AND id=7; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=435 AND id=8; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre' WHERE menu_id=435 AND id=11; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Barbier' WHERE menu_id=435 AND id=12; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc2='Lexique de puissance' WHERE menu_id=435 AND id=13; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc2='Lexique de puissance' WHERE menu_id=721 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=740 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=740 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=740 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=740 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=740 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=740 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=751 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=751 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=751 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=751 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=751 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=751 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=751 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=751 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=751 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=751 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=751 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=751 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=1942 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=1942 AND id=2; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=1942 AND id=3; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=1942 AND id=4; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=1942 AND id=5; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=1942 AND id=6; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=1942 AND id=7; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=1942 AND id=9; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=1942 AND id=10; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=1942 AND id=11; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=1942 AND id=12; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=1942 AND id=13; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=1942 AND id=15; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=1942 AND id=16; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=1949 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=1949 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=1949 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=1949 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=1949 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=1949 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=1949 AND id=6; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=1949 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=1949 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Barbier' WHERE menu_id=1951 AND id=5; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc2='Hôtel des ventes' WHERE menu_id=2121 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des griffons' WHERE menu_id=2121 AND id=3; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des guildes' WHERE menu_id=2121 AND id=4; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boite aux lettres' WHERE menu_id=2121 AND id=6; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=2121 AND id=7; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre' WHERE menu_id=2121 AND id=9; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Barbier' WHERE menu_id=2121 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=2144 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=2144 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=2144 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=2144 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=2144 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=2144 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=2144 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=2144 AND id=7; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=2168 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=2168 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=2168 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=2168 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=2168 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=2168 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=2168 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=2168 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=2168 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=2168 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=2168 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=2168 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=2168 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=2343 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=2343 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=2343 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=2343 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=2343 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=2351 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=2351 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=2351 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=2351 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=2351 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=2351 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=2351 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=2351 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=2351 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=2351 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Hôtel des ventes' WHERE menu_id=2352 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des hippogriffes' WHERE menu_id=2352 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des guildes' WHERE menu_id=2352 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boite aux lettres' WHERE menu_id=2352 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=2352 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre' WHERE menu_id=2352 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Lexique de puissance' WHERE menu_id=2352 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=2847 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=2847 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=2847 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=2847 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=2847 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=2847 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=2847 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=2847 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=2847 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=2847 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=2847 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=2847 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=2847 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=2848 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=2848 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=2848 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=2848 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=2848 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=2848 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Barbier' WHERE menu_id=2849 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc2='Serrurier' WHERE menu_id=2849 AND id=14; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc2='Hôtel des ventes' WHERE menu_id=3127 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc2='Banque' WHERE menu_id=3127 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc2='Auberge' WHERE menu_id=3127 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=3283 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=3283 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=3283 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=3283 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=3283 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=3283 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=3283 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=3284 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=3284 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=3284 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=3284 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=3284 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=3284 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=3284 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=3284 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=3284 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=3284 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=3284 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=3284 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=3284 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=3329 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=3329 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=3329 AND id=2; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=3329 AND id=3; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=3330 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=3330 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=3330 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=3330 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=3330 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=3330 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=3330 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=3330 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=3330 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=3330 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=3330 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=3330 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=3354 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=3354 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=3354 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=3354 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=3354 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=3354 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=3355 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=3355 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=3355 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=3355 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=3355 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=3355 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=3355 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=3355 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=3355 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=3355 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=3355 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=3355 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=3355 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Banque' WHERE menu_id=3506 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des griffons' WHERE menu_id=3506 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des guildes' WHERE menu_id=3506 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Auberge' WHERE menu_id=3506 AND id=3; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=3506 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=3519 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=3519 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=3519 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=3519 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=3519 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=3519 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=3519 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=3519 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=3519 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=3532 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=3532 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=3532 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=3532 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=3532 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=3532 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=3532 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=3532 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=3532 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=3532 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=3532 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=3532 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=3532 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Banque' WHERE menu_id=3533 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des griffons' WHERE menu_id=3533 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des guildes' WHERE menu_id=3533 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=3533 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=3545 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=3545 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=3545 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=3545 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=3545 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=3545 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=3545 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=3558 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=3558 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=3558 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=3558 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=3558 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=3558 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=3558 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=3558 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=3558 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=3558 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=3558 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=3558 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=3558 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=3564 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=3564 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=3564 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=3564 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=3564 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=3572 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=3572 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=3572 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=3572 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=3572 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=3572 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=3572 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=3572 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=3572 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=3572 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=3580 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Gul\'dan' WHERE menu_id=4764 AND id=0; /* option_text: Gul\'dan */
UPDATE locales_gossip_menu_option SET option_text_loc2='Kel\'Thuzad' WHERE menu_id=4764 AND id=1; /* option_text: Kel\'Thuzad */
UPDATE locales_gossip_menu_option SET option_text_loc2='Masse' WHERE menu_id=5222 AND id=2; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc2='Bâton' WHERE menu_id=5222 AND id=4; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc2='Masse' WHERE menu_id=5262 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc2='Masse' WHERE menu_id=5268 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc2='Bâton' WHERE menu_id=5268 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc2='Masse' WHERE menu_id=5270 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc2='Masse' WHERE menu_id=5272 AND id=3; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc2='Bâton' WHERE menu_id=5274 AND id=4; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc2='Masse' WHERE menu_id=5276 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc2='Bâton' WHERE menu_id=5276 AND id=6; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître d\'armes' WHERE menu_id=7633 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=7649 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=7649 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=7649 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=7649 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=7649 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=7649 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=7649 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=7667 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=7667 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=7667 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=7667 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=7667 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=7667 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=7667 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=7667 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=7667 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=7667 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=7667 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=7667 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=7667 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=7667 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des hippogriffes' WHERE menu_id=7777 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître d\'armes' WHERE menu_id=7777 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre de l\'arène' WHERE menu_id=7786 AND id=0; /* option_text: Arena Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=7787 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=7787 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=7787 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=7787 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=7787 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=7787 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=7787 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=7788 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=7788 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=7788 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=7788 AND id=3; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=7788 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=7788 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=7788 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=7788 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=7788 AND id=8; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=7788 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=7788 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=7788 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=7788 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=7788 AND id=13; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Auberge de Lune-d\'Argent' WHERE menu_id=7845 AND id=0; /* option_text: Silvermoon City Inn */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des hippogriffes' WHERE menu_id=8129 AND id=1; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=8137 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=8137 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=8137 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=8137 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=8137 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=8137 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=8137 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=8138 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=8138 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=8138 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=8138 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=8138 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=8138 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=8138 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=8138 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=8138 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=8138 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=8138 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=8138 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=8138 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=8138 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=8196 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=8196 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=8196 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=8196 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=8196 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=8196 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=8196 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=8205 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=8205 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=8205 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=8205 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=8205 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=8205 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=8205 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=8205 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=8205 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=8205 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=8205 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=8205 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=8205 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=8205 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Banque' WHERE menu_id=8282 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc2='Auberge' WHERE menu_id=8282 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de vol' WHERE menu_id=8282 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boite aux lettres' WHERE menu_id=8282 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=8282 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre' WHERE menu_id=8282 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Laboratoire d\'alchimie' WHERE menu_id=8282 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=8326 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=8326 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=8326 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=8326 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=8326 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=8326 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=8326 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=8326 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Banque' WHERE menu_id=8357 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc2='Auberge' WHERE menu_id=8357 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de vol' WHERE menu_id=8357 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boite aux lettres' WHERE menu_id=8357 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=8357 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre' WHERE menu_id=8357 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Laboratoire d\'alchimie' WHERE menu_id=8357 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=8403 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=8403 AND id=2; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=8403 AND id=3; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=8403 AND id=4; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=8403 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=8403 AND id=6; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=8403 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=8403 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Banque' WHERE menu_id=8419 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc2='Auberge' WHERE menu_id=8419 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de vol' WHERE menu_id=8419 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boite aux lettres' WHERE menu_id=8419 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=8419 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre' WHERE menu_id=8419 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Laboratoire d\'alchimie' WHERE menu_id=8419 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=8424 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=8424 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=8424 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=8424 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=8424 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=8424 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=8424 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=8424 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Bâton' WHERE menu_id=8590 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc2='Masse' WHERE menu_id=8611 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc2='Bâton' WHERE menu_id=8611 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=8994 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=8994 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=8995 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=8996 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=8996 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=8997 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=8997 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=8999 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=8999 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=9000 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9001 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=9001 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9002 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=9002 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9017 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=9017 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9018 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=9018 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9025 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=9025 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9026 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le club de la Bière du mois' WHERE menu_id=9026 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc2='La Dame Mehley' WHERE menu_id=9038 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9038 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9040 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='La Dame Mehley' WHERE menu_id=9041 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc2='La Dame Mehley' WHERE menu_id=9042 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9042 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='La Dame Mehley' WHERE menu_id=9043 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9043 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9073 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le Caprice de la vierge' WHERE menu_id=9074 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9074 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le Caprice de la vierge' WHERE menu_id=9075 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le Caprice de la vierge' WHERE menu_id=9076 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9076 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Fusée-de-néant X-51' WHERE menu_id=9191 AND id=0; /* option_text: X-51 Nether-Rocket */
UPDATE locales_gossip_menu_option SET option_text_loc2='Machine météorologique gobeline - Prototype 01-B' WHERE menu_id=9191 AND id=2; /* option_text: Goblin Weather Machine - Prototype 01-B */
UPDATE locales_gossip_menu_option SET option_text_loc2='Jeune hippogriffe' WHERE menu_id=9192 AND id=1; /* option_text: Hippogryph Hatchling */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tortue de monte' WHERE menu_id=9192 AND id=2; /* option_text: Riding Turtle */
UPDATE locales_gossip_menu_option SET option_text_loc2='Feu d\'artifice violet perpétuel' WHERE menu_id=9193 AND id=1; /* option_text: Perpetual Purple Firework */
UPDATE locales_gossip_menu_option SET option_text_loc2='Idole d\'ogre sculptée' WHERE menu_id=9193 AND id=2; /* option_text: Carved Ogre Idol */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tabard des Arcanes' WHERE menu_id=9193 AND id=3; /* option_text: Tabard of the Arcane */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tabard de la brillance' WHERE menu_id=9193 AND id=4; /* option_text: Tabard of Brilliance */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tabard du défenseur' WHERE menu_id=9193 AND id=5; /* option_text: Tabard of the Defender */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tabard de la fureur' WHERE menu_id=9193 AND id=6; /* option_text: Tabard of Fury */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tabard de la nature' WHERE menu_id=9193 AND id=7; /* option_text: Tabard of Nature */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tabard du Vide' WHERE menu_id=9193 AND id=8; /* option_text: Tabard of the Void */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boîte à familiers de Landro' WHERE menu_id=9193 AND id=9; /* option_text: Landro\'s Pet Box */
UPDATE locales_gossip_menu_option SET option_text_loc2='Panier à pique-nique' WHERE menu_id=9194 AND id=0; /* option_text: Picnic Basket */
UPDATE locales_gossip_menu_option SET option_text_loc2='Diabloboule' WHERE menu_id=9194 AND id=2; /* option_text: Imp in a Ball */
UPDATE locales_gossip_menu_option SET option_text_loc2='Marmite de gumbo gobelin' WHERE menu_id=9195 AND id=0; /* option_text: Goblin Gumbo Kettle */
UPDATE locales_gossip_menu_option SET option_text_loc2='Siège de pêche' WHERE menu_id=9195 AND id=1; /* option_text: Fishing Chair */
UPDATE locales_gossip_menu_option SET option_text_loc2='Rênes de tigre spectral' WHERE menu_id=9195 AND id=2; /* option_text: Reins of the Spectral Tiger */
UPDATE locales_gossip_menu_option SET option_text_loc2='Kit de machine volante en papier' WHERE menu_id=9196 AND id=0; /* option_text: Paper Flying Machine Kit */
UPDATE locales_gossip_menu_option SET option_text_loc2='Poulet-fusée' WHERE menu_id=9196 AND id=1; /* option_text: Rocket Chicken */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cerf-volant dragon' WHERE menu_id=9196 AND id=2; /* option_text: Dragon Kite */
UPDATE locales_gossip_menu_option SET option_text_loc2='À travers la Porte des ténèbres' WHERE menu_id=9197 AND id=1; /* option_text: Through the Dark Portal */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9558 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Nourriture & boissons' WHERE menu_id=9559 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voie d\'Illidan' WHERE menu_id=9629 AND id=0; /* option_text: Path of Illidan */
UPDATE locales_gossip_menu_option SET option_text_loc2='Marchand-d\'âme éthérien' WHERE menu_id=9629 AND id=2; /* option_text: Ethereal Soul-Trader */
UPDATE locales_gossip_menu_option SET option_text_loc2='E.N.G.I.N. festif' WHERE menu_id=9682 AND id=0; /* option_text: Party G.R.E.N.A.D.E. */
UPDATE locales_gossip_menu_option SET option_text_loc2='Drapeau de provocation' WHERE menu_id=9682 AND id=1; /* option_text: The Flag of Ownership */
UPDATE locales_gossip_menu_option SET option_text_loc2='Arène' WHERE menu_id=10043 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc2='Barbier' WHERE menu_id=10043 AND id=3; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc2='Serrurier' WHERE menu_id=10043 AND id=9; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc2='Quartier commerçant' WHERE menu_id=10056 AND id=5; /* option_text: Trade District */
UPDATE locales_gossip_menu_option SET option_text_loc2='Lexique de puissance' WHERE menu_id=10056 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=10078 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=10078 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=10078 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=10078 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=10078 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=10078 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=10078 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=10078 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=10078 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Joaillerie' WHERE menu_id=10078 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=10078 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=10078 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=10078 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=10078 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des mages' WHERE menu_id=10082 AND id=3; /* option_text: Mage Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc2='Arène' WHERE menu_id=10106 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc2='Banque' WHERE menu_id=10106 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc2='Auberge' WHERE menu_id=10106 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc2='Armures de cuir' WHERE menu_id=10170 AND id=1; /* option_text: Leather Armor */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cottes de mailles' WHERE menu_id=10170 AND id=2; /* option_text: Mail Armor */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boucliers' WHERE menu_id=10170 AND id=4; /* option_text: Shields */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des joailliers' WHERE menu_id=10173 AND id=6; /* option_text: Jewelcrafting Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc2='Composants' WHERE menu_id=10173 AND id=9; /* option_text: Reagents */
UPDATE locales_gossip_menu_option SET option_text_loc2='Armes' WHERE menu_id=10173 AND id=13; /* option_text: Weapons */
UPDATE locales_gossip_menu_option SET option_text_loc2='Hôtel des ventes' WHERE menu_id=10265 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des hippogriffes' WHERE menu_id=10265 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des guildes' WHERE menu_id=10265 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Boite aux lettres' WHERE menu_id=10265 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître des écuries' WHERE menu_id=10265 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc2='Maître de guerre' WHERE menu_id=10265 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Lexique de puissance' WHERE menu_id=10265 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tigre de bac à sable' WHERE menu_id=10330 AND id=0; /* option_text: Sandbox Tiger */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chemise violette épique' WHERE menu_id=10330 AND id=1; /* option_text: Epic Purple Shirt */
UPDATE locales_gossip_menu_option SET option_text_loc2='Râtelier d\'épées en mousse' WHERE menu_id=10330 AND id=2; /* option_text: Foam Sword Rack */
UPDATE locales_gossip_menu_option SET option_text_loc2='Sentier de Cénarius' WHERE menu_id=10533 AND id=0; /* option_text: Path of Cenarius */
UPDATE locales_gossip_menu_option SET option_text_loc2='Piñata ogre' WHERE menu_id=10533 AND id=1; /* option_text: Ogre Pinata */
UPDATE locales_gossip_menu_option SET option_text_loc2='Poulet magique' WHERE menu_id=10533 AND id=2; /* option_text: Magic Rooster */
UPDATE locales_gossip_menu_option SET option_text_loc2='Toundra Boréenne' WHERE menu_id=10668 AND id=0; /* option_text: Borean Tundra */
UPDATE locales_gossip_menu_option SET option_text_loc2='Fjord Hurlant' WHERE menu_id=10668 AND id=1; /* option_text: Howling Fjord */
UPDATE locales_gossip_menu_option SET option_text_loc2='Alchimie' WHERE menu_id=10767 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc2='Forge' WHERE menu_id=10767 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=10767 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Enchantement' WHERE menu_id=10767 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc2='Ingénieurs' WHERE menu_id=10767 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc2='Secourisme' WHERE menu_id=10767 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=10767 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=10767 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=10767 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Travail du cuir' WHERE menu_id=10767 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Minage' WHERE menu_id=10767 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc2='Dépeçage' WHERE menu_id=10767 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc2='Tailleur' WHERE menu_id=10767 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc2='Mage' WHERE menu_id=10768 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc2='Paladin' WHERE menu_id=10768 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=10768 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=10768 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=10768 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=10768 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Barbier' WHERE menu_id=10769 AND id=2; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc2='Serrurier' WHERE menu_id=10769 AND id=7; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cerf-volant rohart' WHERE menu_id=10810 AND id=1; /* option_text: Tuskarr Kite */
UPDATE locales_gossip_menu_option SET option_text_loc2='Bébé tigre spectral' WHERE menu_id=10810 AND id=2; /* option_text: Spectral Tiger Cub */
UPDATE locales_gossip_menu_option SET option_text_loc2='Hall des Champions' WHERE menu_id=11845 AND id=0; /* option_text: Champions\' Hall */
UPDATE locales_gossip_menu_option SET option_text_loc2='Le Parc' WHERE menu_id=11845 AND id=2; /* option_text: The Park */
UPDATE locales_gossip_menu_option SET option_text_loc2='Donjon de Hurlevent' WHERE menu_id=11845 AND id=5; /* option_text: Stormwind Keep */
UPDATE locales_gossip_menu_option SET option_text_loc2='Hôtel des ventes' WHERE menu_id=11848 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc2='Eleveuse de chevaux' WHERE menu_id=11848 AND id=4; /* option_text: Horse Breeder */
UPDATE locales_gossip_menu_option SET option_text_loc2='Barbier' WHERE menu_id=11969 AND id=5; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc2='Druide' WHERE menu_id=11976 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chasseur' WHERE menu_id=11976 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc2='Prêtre' WHERE menu_id=11976 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc2='Voleuse' WHERE menu_id=11976 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc2='Chaman' WHERE menu_id=11976 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc2='Démoniste' WHERE menu_id=11976 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc2='Guerrier' WHERE menu_id=11976 AND id=7; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc2='Cuisinier' WHERE menu_id=11977 AND id=0; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc2='Herboristerie' WHERE menu_id=11977 AND id=1; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc2='Calligraphie' WHERE menu_id=11977 AND id=2; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc2='Pêche' WHERE menu_id=11977 AND id=3; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc2='Fournitures générales' WHERE menu_id=11978 AND id=0; /* option_text: General Goods */
UPDATE locales_gossip_menu_option SET option_text_loc2='Poisons & composants' WHERE menu_id=11978 AND id=1; /* option_text: Poisons & Reagents */
UPDATE locales_gossip_menu_option SET option_text_loc2='Fournitures d\'artisanat' WHERE menu_id=11978 AND id=3; /* option_text: Trade Supplies */
UPDATE locales_gossip_menu_option SET option_text_loc2='Vallée de la Force' WHERE menu_id=12637 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc2='Vallée de l\'Honneur' WHERE menu_id=12637 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc2='Vallée de la Force' WHERE menu_id=12638 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc2='Vallée de l\'Honneur' WHERE menu_id=12638 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc2='Vallée de la Force' WHERE menu_id=12639 AND id=0; /* option_text: Valley of Strength */
UPDATE locales_gossip_menu_option SET option_text_loc2='Vallée de l\'Honneur' WHERE menu_id=12639 AND id=1; /* option_text: Valley of Honor */
UPDATE locales_gossip_menu_option SET option_text_loc2='Faucon-dragon amani' WHERE menu_id=12785 AND id=2; /* option_text: Amani Dragonhawk */

SET NAMES 'latin1';
